// Deep-systems ECAM bridge (docs/deep/ecam_bridge.md).
//
// This file is hand-written and static: it holds no per-alert data. Two
// things are spliced around it by src/deep/ecam/patches.rs's SourcePatches:
//
//  1. Separately, at each bundle's module scope: a plain-data
//     `Object.assign(EcamAbnormalSensedProcedures, {...})` in EWD.js AND
//     SystemsHost.js, and the same for `EcamInopSys`/`EcamInfos` in sdv2.js
//     -- the STATUS page, the only bundle in this build that resolves
//     either id to text. Title/items/STATUS/INOP text, static, never
//     touches `SimVar` or `FwsCore`, generated by
//     `codegen::procedures_merge_js` and friends.
//  2. Inside SystemsHost.js's `FwsCore.update(_deltaTime)`, this file's own
//     source text, immediately followed by a generated
//     `const __deepEcamAlerts = [...]` (`codegen::alerts_js_array`) and a
//     call to `installDeepEcam` below, all guarded to run once per `FwsCore`
//     instance (the A380 runs two, FWS1/FWS2, each its own instance in this
//     same compiled file).
//
// `installDeepEcam` only ever builds the dynamic half FlyByWire calls
// `EwdAbnormalItem` -- trigger state and per-line shown/checked state -- and
// adds it directly to `fws.ewdAbnormal`/`fws.allSuppressableItems` (and
// `fws.abnormalSensed.ewdAbnormalSensed`, which is where that third dict
// really lives -- it is FwsAbnormalSensed's, not FwsCore's) (all three
// already exist and are live plain
// objects by the time `update()` first runs: FwsCore's own constructor
// builds `ewdAbnormal`/`allSuppressableItems` as one-time snapshots of
// `abnormalSensed.ewdAbnormalSensed` (FwsCore.ts:2339-2356), so entries
// added here go into all three explicitly, not through that copy). From
// then on FlyByWire's own per-tick loop
// (`Object.entries(this.ewdAbnormal)`, FwsCore.ts:5537) reads them exactly
// like its own native alerts: sorts them by failure level, requests the
// master warning/caution light, drives the aural (FwsSoundManager reads the
// same `requestMasterWarningFromFaults`/`requestMasterCautionFromFaults`
// this loop sets), and renders their procedure lines.
//
// Design note: rather than trying to build genuine `Subject`/`MappedSubject`
// instances (msfs-sdk classes bundled as local, non-exported bindings
// private to each compiled file -- unreachable from a separately loaded
// script), `makeFlag` below only ever implements the two members FlyByWire's
// own FwsCore actually calls on a procedure's `simVarIsActive`: `.get()`
// (every tick, from that same `Object.entries` loop) and `.sub()`, which
// FwsCore only ever calls once, at its own construction time, over the
// `allSuppressableItems` snapshot that predates these entries -- so it is
// never actually called on them, and a no-op is enough for correctness.
// This keeps the whole shim dependent on nothing but `SimVar`, which
// genuinely is a global (src/js/msfs/simvar.js: `globalThis.SimVar =
// SimVar;`), unlike everything from `@microsoft/msfs-sdk`.
//
// Confirm delays, phase inhibits, per-line shown/hidden timing ("AFTER n S")
// and procedure-line completion are evaluated the same way
// `deep::api::Ecam::update` does in src/deep/api.rs, from the same `Cond`
// trees (encoded here as small tagged arrays, not JS source text, so
// nothing here ever calls `eval`).
(function (global) {
  'use strict';

  function readVar(name, unit) {
    try {
      var v = global.SimVar.GetSimVarValue(name, unit);
      return typeof v === 'number' ? v : Number(v) || 0;
    } catch (e) {
      return 0;
    }
  }

  var CMP = {
    lt: function (a, b) { return a < b; },
    le: function (a, b) { return a <= b; },
    gt: function (a, b) { return a > b; },
    ge: function (a, b) { return a >= b; },
    eq: function (a, b) { return Math.abs(a - b) < 1e-9; },
    ne: function (a, b) { return Math.abs(a - b) >= 1e-9; },
  };

  // A condition is one of:
  //   ["always"]
  //   ["var", name, unit, cmp, value]
  //   ["varvar", nameA, unitA, cmp, nameB, unitB]
  //   ["and", [cond, ...]] | ["or", [cond, ...]] | ["not", [cond]]
  // matching src/deep/api.rs's `Cond`, encoded by
  // src/deep/ecam/cond_json.rs's `cond_to_js`.
  function evalCond(c) {
    switch (c[0]) {
      case 'always':
        return true;
      case 'var':
        return CMP[c[3]](readVar(c[1], c[2]), c[4]);
      case 'varvar':
        return CMP[c[3]](readVar(c[1], c[2]), readVar(c[4], c[5]));
      case 'and':
        for (var i = 0; i < c[1].length; i++) {
          if (!evalCond(c[1][i])) return false;
        }
        return true;
      case 'or':
        for (var j = 0; j < c[1].length; j++) {
          if (evalCond(c[1][j])) return true;
        }
        return false;
      case 'not':
        return !evalCond(c[1][0]);
      default:
        return false;
    }
  }
  global.__deepEcamEvalCond = evalCond;

  // A `Subscribable<boolean>`-shaped stand-in; see the file doc comment for
  // why a real msfs-sdk Subject is neither reachable nor necessary here.
  function makeFlag(initial) {
    var v = !!initial;
    return {
      get: function () { return v; },
      set: function (x) { v = !!x; },
      sub: function () { /* never called: see file doc comment */ },
    };
  }

  // One alert definition's live timers: how long its trigger has read true
  // (gates `confirmS`) and how long the alert itself has been shown (gates
  // each line's `afterS`), exactly mirroring `Ecam::update`'s `held_s` and
  // `shown_s` maps in src/deep/api.rs.
  function makeAlertRuntime(def) {
    var heldS = 0;
    var shownS = 0;
    var flag = makeFlag(false);
    return {
      // FlyByWire's own `EwdAbnormalItem` for this id (FwsCore.ts:24-77).
      item: {
        flightPhaseInhib: def.flightPhaseInhib,
        simVarIsActive: flag,
        notActiveWhenItemActive: [],
        monitorConfirmTime: 0,
        whichItemsToShow: function () {
          return def.items.map(function (it) {
            return evalCond(it.appliesIf) && shownS >= it.afterS;
          });
        },
        whichItemsChecked: function () {
          return def.items.map(function (it) {
            return it.doneWhen ? evalCond(it.doneWhen) : false;
          });
        },
        failure: def.failure,
        sysPage: def.sysPage,
        // Present only when this alert actually has STATUS/INOP SYS lines
        // (their text was already merged into sdv2.js's `EcamInopSys`/
        // `EcamInfos` by the static patch; these just name which ids apply while
        // this alert is active -- FwsCore.ts:5715, :5714's
        // `pushKeyUnique(value.inopSysAllPhases/.info, ...)`).
        inopSysAllPhases: def.inopIds.length ? function () { return def.inopIds; } : undefined,
        info: def.infoIds.length ? function () { return def.infoIds; } : undefined,
      },
      step: function (dtS) {
        var triggered = evalCond(def.trigger);
        heldS = triggered ? heldS + Math.max(dtS, 0) : 0;
        var active = triggered && heldS >= def.confirmS;
        shownS = active ? shownS + Math.max(dtS, 0) : 0;
        flag.set(active);
      },
    };
  }

  // Called once per `FwsCore` instance, the first time it ticks (see the
  // file doc comment for why that is early enough): adds every alert's
  // `EwdAbnormalItem` straight into the three live dicts FlyByWire's own
  // per-tick loop reads, and returns the per-tick stepper the caller keeps
  // calling from then on.
  global.installDeepEcam = function (fws, defs) {
    // The two dicts FlyByWire's own per-tick loop actually reads live
    // (`Object.entries(this.ewdAbnormal)`, `this.allSuppressableItems[...]`)
    // are FwsCore's own; `ewdAbnormalSensed` belongs to its FwsAbnormalSensed
    // (`this.abnormalSensed`, SystemsHost.js:177141), NOT to FwsCore --
    // `fws.ewdAbnormalSensed` is undefined. Nothing reads that third dict
    // per tick (only FwsAbnormalSensed.destroy() walks it, and skips an
    // entry whose simVarIsActive has no `destroy`, which ours has not), but
    // a sensed abnormal belongs in it, so it is filled when it is there.
    // Everything here is guarded: this runs inside FwsCore.update(), where a
    // thrown TypeError would take the whole flight-warning system down.
    if (!fws || !fws.ewdAbnormal || !fws.allSuppressableItems) {
      return function () {};
    }
    var sensed = fws.abnormalSensed && fws.abnormalSensed.ewdAbnormalSensed;
    var runtimes = defs.map(function (def) {
      var rt = makeAlertRuntime(def);
      if (sensed) {
        sensed[def.id] = rt.item;
      }
      fws.ewdAbnormal[def.id] = rt.item;
      fws.allSuppressableItems[def.id] = rt.item;
      return rt;
    });
    var lastMs = Date.now();
    return function stepAll() {
      var nowMs = Date.now();
      var dtS = Math.min(Math.max((nowMs - lastMs) / 1000, 0), 1);
      lastMs = nowMs;
      for (var i = 0; i < runtimes.length; i++) {
        runtimes[i].step(dtS);
      }
    };
  };
})(globalThis);
