//! The plugin's own `src/deep` files, compiled here unchanged, except its
//! X-Plane host (`plugin.rs`) and X-Plane glue in `integration`.
#[path = "../../../../src/deep/api.rs"]
pub mod api;
#[path = "../../../../src/deep/apu/mod.rs"]
pub mod apu;
#[path = "../../../../src/deep/autoflight/mod.rs"]
pub mod autoflight;
#[path = "../../../../src/deep/avionics_network/mod.rs"]
pub mod avionics_network;
#[path = "../../../../src/deep/breakers/mod.rs"]
pub mod breakers;
#[path = "../../../../src/deep/cabin/mod.rs"]
pub mod cabin;
#[path = "../../../../src/deep/communications/mod.rs"]
pub mod communications;
#[path = "../../../../src/deep/ecam/mod.rs"]
pub mod ecam;
#[path = "../../../../src/deep/electrical/mod.rs"]
pub mod electrical;
#[path = "../../../../src/deep/engine_accessories/mod.rs"]
pub mod engine_accessories;
#[path = "../../../../src/deep/environment/mod.rs"]
pub mod environment;
#[path = "../../../../src/deep/fire_ice/mod.rs"]
pub mod fire_ice;
#[path = "../../../../src/deep/flight_controls/mod.rs"]
pub mod flight_controls;
#[path = "../../../../src/deep/fuel/mod.rs"]
pub mod fuel;
#[path = "../../../../src/deep/gear_structure/mod.rs"]
pub mod gear_structure;
#[path = "../../../../src/deep/hydraulics/mod.rs"]
pub mod hydraulics;
#[path = "../../../../src/deep/oxygen/mod.rs"]
pub mod oxygen;
#[path = "../../../../src/deep/pneumatic_ducts/mod.rs"]
pub mod pneumatic_ducts;
#[path = "../../../../src/deep/sensors/mod.rs"]
pub mod sensors;
#[path = "../../../../src/deep/thermal_zones/mod.rs"]
pub mod thermal_zones;
#[path = "../../../../src/deep/wiring/mod.rs"]
pub mod wiring;
#[path = "../../../../src/deep/frame.rs"]
pub mod frame;
#[path = "../../../../src/deep/live.rs"]
pub mod live;
#[path = "../../../../src/deep/lvar_bridge.rs"]
pub mod lvar_bridge;
#[path = "../../../../src/deep/msfs_inputs.rs"]
pub mod msfs_inputs;
#[path = "../../../../src/deep/weather.rs"]
pub mod weather;
pub mod integration;
#[path = "../../../../src/deep/all_registry.rs"]
mod all_registry;
pub use all_registry::registry;
