"""Build the EFB Study payload from the X-Plane Study app.

The pages are app/ui/index.html. Nothing in it is edited by hand: this
splits that one file into the pieces the EFB can actually load, lowers its
syntax to what the EFB's browser understands, and appends a palette.

Why a split at all. Coherent GT, the EFB's browser, refuses every way of
running code that arrives as a string: a <script> element created at runtime
is silently not executed, and the Function constructor throws. The only
mechanism that works is a real file listed in efb.html's import-script --
the same way study.js itself loads. So the app's single script block is
written out as its own file, wrapped in a function, and study.js calls it
once the markup is in the document.

Outputs into dist/:
  study-app.html          markup and styles, script block removed
  study-app.js            the app's code, transpiled, as window.__deepStudyStart
  study.js                the loader
  test/study-fixture.json
"""

import io
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
SRC = os.path.join(ROOT, 'app', 'ui', 'index.html')
FIXTURE = os.path.join(ROOT, 'app', 'ui', 'test', 'study-fixture.json')
OUT = os.path.join(HERE, 'dist')
FBW = os.environ.get('FBW_AIRCRAFT', 'D:\\fbw-aircraft')

BASE = '/Pages/VCockpit/Instruments/A380X/EFB/'

# Tabs the app has that the EFB should not show.
#
# The tablet already is a tablet: FlyByWire give it ground services, settings
# and a status page of their own, and theirs are the ones wired to MSFS. Ours
# would sit beside them saying different things. The last three are worse than
# redundant -- Flight Plan, Status and Support talk to the X-Plane plugin's
# HTTP port, which does not exist in MSFS at all.
#
# Hidden rather than deleted: the panels stay in the document, so any of the
# app's code that looks them up still finds them. Only the way in is removed.
HIDDEN_TABS = ('flightplan', 'ground', 'settings', 'status', 'support')

PALETTE = """
<style id="efb-palette">
  /* The X-Plane app's own colours, restated for the EFB. Appended rather
     than edited so app/ui/index.html stays a byte-for-byte source. */
  :root {
    --bg: #0d1218;
    --panel: #0d1218;
    --line: #5c6b7a;
    --line-dim: #2f3a45;
    --text: #eef4f9;
    --text-dim: #93a3b2;
    --heading: #93a3b2;
    --field: #06090d;
    --button: #1d2732;
    --button-line: #5c6b7a;
    --accent: #00c2cc;
    --ok: #3ccf6e;
    --warn: #e8a33d;
    --bad: #e05c5c;
  }
  html, body { width: 100%; height: 100%; margin: 0; overflow: hidden; }
  /* The footer belongs to the standalone app: its logo, its own branding,
     and the address of a plugin port that does not exist here. */
  footer { display: none; }

  /* The app collapses its sidebar under @media (max-width: 1100px), and the
     EFB's viewport is narrower than that in CSS pixels -- so its phone
     layout fires on what is actually a wide landscape instrument, stacking
     the chapter nav above the content. Put the sidebar back. These follow
     the media block in source order, so they win at equal specificity. */
  .study-layout {
    grid-template-columns: clamp(150px, 18vw, 230px) minmax(0, 1fr);
    padding: 0 var(--gutter);
  }
  .study-nav {
    border-right: 2px solid var(--line-dim);
    border-bottom: 0;
    max-height: none;
    padding: 0 10px 0 0;
  }
  .study-nav button { display: block; width: 100%; }
  .study-nav-group { margin: 14px 0 4px; }
%HIDDEN_TABS%
</style>
"""

HEADER = (
    '// Generated by build.py from app/ui/index.html. Do not edit.\n'
    '// The Study app, wrapped so study.js can start it once its markup is in\n'
    '// the document, and transpiled: the EFB\'s browser cannot parse the\n'
    '// optional chaining and nullish coalescing the app uses.\n'
)


def transpile(path):
    """Lower the app's syntax to what the EFB's browser can parse.

    Coherent GT in MSFS 2020 is an older Chromium. It does not understand
    optional chaining (`?.`) or nullish coalescing (`??`), both of which the
    app uses -- and a parse error takes the *whole file* with it. So the
    symptom is not a broken feature: it is a global that never appears and a
    panel reporting that study-app.js did not load.

    es2017 keeps async/await and template literals, which that engine does
    handle, and lowers the two it does not. esbuild comes from FlyByWire's
    own node_modules, which their instrument build already depends on.
    """
    exe = 'esbuild.CMD' if os.name == 'nt' else 'esbuild'
    esbuild = os.path.join(FBW, 'node_modules', '.bin', exe)
    if not os.path.exists(esbuild):
        sys.exit(
            'no esbuild at ' + esbuild + '\n'
            'Set FBW_AIRCRAFT to the aircraft repo. Without transpiling, the\n'
            "EFB cannot parse the app and the Study panel stays empty.")

    result = subprocess.run(
        [esbuild, path, '--target=es2017'], capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit('esbuild failed:\n' + result.stderr)

    io.open(path, 'w', encoding='utf8', newline='\n').write(HEADER + result.stdout)

    # Prove the lowering actually happened rather than trusting the flag.
    lowered = io.open(path, encoding='utf8').read()
    for token, what in (('?.', 'optional chaining'), ('??', 'nullish coalescing')):
        if token in lowered:
            sys.exit('esbuild left ' + what + ' in the output; the EFB will not parse it.')


def main():
    if not os.path.exists(SRC):
        sys.exit('missing ' + SRC)

    html = io.open(SRC, encoding='utf8', newline='').read()

    match = re.search(r'<script>(.*?)</script>', html, re.S)
    if not match:
        sys.exit('no <script> block in index.html -- has it been restructured?')
    code = match.group(1)

    # Two substitutions, both exact, both because the EFB is not the app's own
    # window. The app picks between the plugin's HTTP port and its static
    # fixture from its query string; there is no query string here and no
    # plugin in MSFS, so pin it to fixture mode. Its one relative fetch has to
    # become absolute, since the EFB's document lives at a different path.
    before = code
    code = code.replace(
        "new URLSearchParams(location.search).get('fixture') === '1'", 'true')
    code = code.replace(
        "fetch('test/study-fixture.json')",
        "fetch('" + BASE + "test/study-fixture.json')")
    if code == before:
        sys.exit('neither substitution applied -- the app changed, check build.py')

    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    os.makedirs(os.path.join(OUT, 'test'))

    out_js = os.path.join(OUT, 'study-app.js')
    io.open(out_js, 'w', encoding='utf8', newline='\n').write(
        'window.__deepStudyStart = function () {\n' + code + '\n};\n')
    transpile(out_js)

    # Check the tabs are still called what they were before writing a rule
    # that would otherwise hide nothing and say nothing about it.
    for tab in HIDDEN_TABS:
        if 'data-tab="' + tab + '"' not in html:
            sys.exit('no tab named ' + tab + ' any more -- HIDDEN_TABS is stale')
    hidden = ',\n  '.join('.tab-btn[data-tab="' + t + '"]' for t in HIDDEN_TABS)
    palette = PALETTE.replace(
        '%HIDDEN_TABS%',
        '  /* FlyByWire\'s own tablet covers these, and the last three of them\n'
        '     talk to the X-Plane plugin, which is not here. */\n  '
        + hidden + ' { display: none; }')

    page = html[:match.start()] + html[match.end():] + palette
    io.open(os.path.join(OUT, 'study-app.html'), 'w', encoding='utf8', newline='\n').write(page)

    shutil.copyfile(FIXTURE, os.path.join(OUT, 'test', 'study-fixture.json'))
    shutil.copyfile(os.path.join(HERE, 'study.js'), os.path.join(OUT, 'study.js'))

    for name in ('study-app.html', 'study-app.js', 'study.js', 'test/study-fixture.json'):
        path = os.path.join(OUT, name.replace('/', os.sep))
        print('  {:<24} {:>12,} bytes'.format(name, os.path.getsize(path)))


if __name__ == '__main__':
    main()
