use crate::gates::Gate;

pub const GATES_WAVE3: &[Gate] = &[
    Gate { variable: "ELEC_FMS_1_BREAKER_OPEN", units: &["fms-1-normal-bkr", "fms-1-2nd-bkr"] },
    Gate { variable: "ELEC_FMS_2_BREAKER_OPEN", units: &["fms-2-normal-bkr", "fms-2-2nd-bkr"] },
    Gate { variable: "ELEC_FMS_3_BREAKER_OPEN", units: &["fms-3-normal-bkr", "fms-3-2nd-bkr"] },
    Gate { variable: "ELEC_TCAS_BREAKER_OPEN", units: &["tcas-normal-bkr", "tcas-2nd-bkr"] },
    Gate { variable: "ELEC_WXR_BREAKER_OPEN", units: &["wxr"] },
    Gate { variable: "ELEC_VHF_2_BREAKER_OPEN", units: &["vhf-2"] },
    Gate { variable: "ELEC_ADIRS_1_BREAKER_OPEN", units: &["adirs-1-normal-bkr", "adirs-1-2nd-bkr"] },
    Gate { variable: "ELEC_ADIRS_2_BREAKER_OPEN", units: &["adirs-2-normal-bkr", "adirs-2-2nd-bkr"] },
    Gate { variable: "ELEC_ADIRS_3_BREAKER_OPEN", units: &["adirs-3-normal-bkr", "adirs-3-2nd-bkr"] },
    Gate { variable: "ELEC_FUEL_VALVE_CROSSFEED_1_BREAKER_OPEN", units: &["fuel-valve-crossfeed-1"] },
    Gate { variable: "ELEC_FUEL_VALVE_CROSSFEED_2_BREAKER_OPEN", units: &["fuel-valve-crossfeed-2"] },
    Gate { variable: "ELEC_FUEL_VALVE_CROSSFEED_3_BREAKER_OPEN", units: &["fuel-valve-crossfeed-3"] },
    Gate { variable: "ELEC_FUEL_VALVE_CROSSFEED_4_BREAKER_OPEN", units: &["fuel-valve-crossfeed-4"] },
    Gate { variable: "ELEC_FUEL_VALVE_ENG_LP_1_BREAKER_OPEN", units: &["fuel-valve-eng-lp-1"] },
    Gate { variable: "ELEC_FUEL_VALVE_ENG_LP_2_BREAKER_OPEN", units: &["fuel-valve-eng-lp-2"] },
    Gate { variable: "ELEC_FUEL_VALVE_ENG_LP_3_BREAKER_OPEN", units: &["fuel-valve-eng-lp-3"] },
    Gate { variable: "ELEC_FUEL_VALVE_ENG_LP_4_BREAKER_OPEN", units: &["fuel-valve-eng-lp-4"] },
    Gate { variable: "ELEC_FUEL_VALVE_JETTISON_LEFT_BREAKER_OPEN", units: &["fuel-valve-jettison-left"] },
    Gate { variable: "ELEC_FUEL_VALVE_JETTISON_RIGHT_BREAKER_OPEN", units: &["fuel-valve-jettison-right"] },
    Gate { variable: "ELEC_FUEL_VALVE_APU_FEED_BREAKER_OPEN", units: &["fuel-valve-apu-feed"] },
    Gate { variable: "ELEC_BAT_1_BREAKER_OPEN", units: &["bat-1"] },
    Gate { variable: "ELEC_BAT_2_BREAKER_OPEN", units: &["bat-2"] },
    Gate { variable: "ELEC_BAT_APU_BREAKER_OPEN", units: &["bat-apu"] },
    Gate { variable: "ELEC_BAT_CHARGE_LIMITER_1_BREAKER_OPEN", units: &["bat-charge-limiter-1"] },
    Gate { variable: "ELEC_BAT_CHARGE_LIMITER_2_BREAKER_OPEN", units: &["bat-charge-limiter-2"] },
    Gate { variable: "ELEC_EXT_PWR_CONTACTOR_BREAKER_OPEN", units: &["ext-pwr-contactor"] },
    Gate { variable: "ELEC_APU_ECU_A_BREAKER_OPEN", units: &["apu-ecu-a"] },
    Gate { variable: "ELEC_APU_ECU_B_BREAKER_OPEN", units: &["apu-ecu-b"] },
    Gate { variable: "ELEC_APU_FUEL_SHUTOFF_VALVE_BREAKER_OPEN", units: &["apu-fuel-shutoff-valve"] },
    Gate { variable: "ELEC_LOAD_vhf-2_CUT", units: &["vhf-2"] },
    Gate { variable: "SEC_1_BREAKER_OPEN", units: &["sec-1-normal-bkr", "sec-1-2nd-bkr"] },
    Gate { variable: "SEC_2_BREAKER_OPEN", units: &["sec-2-normal-bkr", "sec-2-2nd-bkr"] },
    Gate { variable: "SEC_3_BREAKER_OPEN", units: &["sec-3-normal-bkr", "sec-3-2nd-bkr"] },
    Gate { variable: "FCDC_1_BREAKER_OPEN", units: &["fcdc-1-normal-bkr", "fcdc-1-2nd-bkr"] },
    Gate { variable: "FCDC_2_BREAKER_OPEN", units: &["fcdc-2-normal-bkr", "fcdc-2-2nd-bkr"] },
    Gate { variable: "ELEC_EGPWC_BREAKER_OPEN", units: &["egpwc"] },
    Gate { variable: "ELEC_FUEL_VALVE_CROSSFEED_1_POS_IND_BREAKER_OPEN", units: &["fuel-valve-crossfeed-1-pos-ind"] },
    Gate { variable: "ELEC_FUEL_VALVE_CROSSFEED_2_POS_IND_BREAKER_OPEN", units: &["fuel-valve-crossfeed-2-pos-ind"] },
    Gate { variable: "ELEC_FUEL_VALVE_CROSSFEED_3_POS_IND_BREAKER_OPEN", units: &["fuel-valve-crossfeed-3-pos-ind"] },
    Gate { variable: "ELEC_FUEL_VALVE_CROSSFEED_4_POS_IND_BREAKER_OPEN", units: &["fuel-valve-crossfeed-4-pos-ind"] },
    Gate { variable: "ELEC_LIGHT_GLARESHIELD_BREAKER_OPEN", units: &["light-glareshield"] },
    Gate { variable: "ELEC_LIGHT_LANDING_BREAKER_OPEN", units: &["light-landing"] },
    Gate { variable: "ELEC_LIGHT_LOGO_BREAKER_OPEN", units: &["light-logo"] },
    Gate { variable: "ELEC_LIGHT_NAV_BREAKER_OPEN", units: &["light-nav"] },
    Gate { variable: "ELEC_LIGHT_PANEL_BREAKER_OPEN", units: &["light-panel"] },
    Gate { variable: "ELEC_LIGHT_PEDESTAL_BREAKER_OPEN", units: &["light-pedestal"] },
    Gate { variable: "ELEC_LIGHT_RECOGNITION_BREAKER_OPEN", units: &["light-recognition"] },
];
