#!/usr/bin/env node
// Merges the per-screen recordings of `npm run reference -- --record`
// (D:/A380/fbw-build/reference-dom-usage/<state>.<SCREEN>.json) into
// docs/dom-usage-recorded.md, for the DOM engineer.
//
//   npm run dom-usage
import fs from 'node:fs';
import path from 'node:path';
import { DOCS_DIR, DOM_USAGE_DIR } from './config.mjs';

const files = fs.existsSync(DOM_USAGE_DIR) ? fs.readdirSync(DOM_USAGE_DIR).filter((f) => f.endsWith('.json')).sort() : [];
if (!files.length) {
  console.error(`no recordings in ${DOM_USAGE_DIR}; run: npm run reference -- --state all --record`);
  process.exit(1);
}

const runs = files.map((f) => {
  const [state, screen] = f.slice(0, -5).split('.');
  return { state, screen, data: JSON.parse(fs.readFileSync(path.join(DOM_USAGE_DIR, f), 'utf8')) };
});
const screens = [...new Set(runs.map((r) => r.screen))];
const states = [...new Set(runs.map((r) => r.state))];

// key -> {count, screens:Set}; counts are the maximum over states per screen,
// summed over screens, so repeated states don't inflate them.
function merge(pick) {
  const perScreen = new Map();
  for (const r of runs) {
    for (const [k, v] of Object.entries(pick(r.data) ?? {})) {
      const n = typeof v === 'number' ? v : v.bundle;
      if (!n) continue;
      const id = `${r.screen}\u0001${k}`;
      perScreen.set(id, Math.max(perScreen.get(id) ?? 0, n));
    }
  }
  const out = new Map();
  for (const [id, n] of perScreen) {
    const [screen, k] = id.split('\u0001');
    const e = out.get(k) ?? { count: 0, screens: new Set() };
    e.count += n;
    e.screens.add(screen);
    out.set(k, e);
  }
  return [...out.entries()].sort((a, b) => b[1].count - a[1].count || a[0].localeCompare(b[0]));
}

const esc = (s) => String(s).replace(/\|/g, '\\|').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const scr = (set) => (set.size === screens.length ? 'all' : [...set].sort().join(', '));
function table(title, rows, head = 'name', note = '') {
  if (!rows.length) return `### ${title}\n\n(none recorded)\n`;
  const lines = [`### ${title}`, ''];
  if (note) lines.push(note, '');
  lines.push(`| ${head} | count | screens |`, '|---|---:|---|');
  for (const [k, e] of rows) lines.push(`| \`${esc(k)}\` | ${e.count} | ${scr(e.screens)} |`);
  return `${lines.join('\n')}\n`;
}

// Host-only API use (the VCockpit shims), listed so it is not mistaken for instrument use.
const hostOnly = new Map();
for (const r of runs) {
  for (const [k, v] of Object.entries(r.data.api)) {
    if (v.bundle === 0 && v.host > 0) hostOnly.set(k, (hostOnly.get(k) ?? 0) + v.host);
  }
}
const bundleApi = merge((d) => d.api);
const bundleKeys = new Set(bundleApi.map(([k]) => k));

const detailGroups = [
  ['Element.setAttribute', 'Attributes set with setAttribute'],
  ['Element.setAttributeNS', 'Attributes set with setAttributeNS'],
  ['Element.getAttribute', 'Attributes read with getAttribute'],
  ['Element.removeAttribute', 'Attributes removed'],
  ['Document.createElementNS', 'createElementNS (namespace, tag)'],
  ['Document.createElement', 'createElement tags'],
  ['Element.insertAdjacentHTML', 'insertAdjacentHTML positions'],
  ['Element.insertAdjacentElement', 'insertAdjacentElement positions'],
  ['CSSStyleDeclaration.setProperty', 'style.setProperty properties'],
  ['CSSStyleDeclaration.removeProperty', 'style.removeProperty properties'],
  ['CSSStyleDeclaration.getPropertyValue', 'style.getPropertyValue properties'],
  ['HTMLCanvasElement.getContext', 'canvas getContext types'],
  ['EventTarget.addEventListener', 'addEventListener event types'],
  ['Element.querySelector', 'Element.querySelector selectors'],
  ['Element.querySelectorAll', 'Element.querySelectorAll selectors'],
  ['Document.querySelector', 'document.querySelector selectors'],
  ['Document.querySelectorAll', 'document.querySelectorAll selectors'],
];
const details = merge((d) => d.details);

const out = [];
out.push('# DOM, CSS and SVG usage recorded in Chromium');
out.push('');
out.push('Generated by `npm run dom-usage` (tools/reference/src/dom-usage.mjs) from');
out.push('`npm run reference -- --state all --record`. Do not edit by hand.');
out.push('');
out.push(`- States: ${states.join(', ')}`);
out.push(`- Screens: ${screens.join(', ')}`);
out.push('');
out.push('What this measures: every method and accessor on the DOM, CSSOM, SVG,');
out.push('Canvas and animation interface prototypes was wrapped with a counter');
out.push('while the real instrument bundles loaded and ran 20 s of frames in each');
out.push('state. Calls are attributed to the first script on the stack, so only');
out.push('calls made from the bundles are listed as instrument use. CSS properties');
out.push('assigned as `el.style.name = v` are recorded through a proxy on `.style`.');
out.push('The end-of-run sections walk the final document and the loaded style');
out.push('sheets. Counts are summed over screens (maximum over states per screen).');
out.push('Code paths a state does not reach (other SD pages, failures, other ND');
out.push('modes) are not recorded; compare with docs/dom-survey.md, which is static.');
out.push('');
out.push('## DOM APIs called by the instruments');
out.push('');
out.push(table('Methods and accessors', bundleApi, 'interface.member', '`get`/`set` mark accessors; `CSSStyleDeclaration[name] set` is a named CSS property assignment.'));
for (const [prefix, title] of detailGroups) {
  const rows = details.filter(([k]) => k.startsWith(`${prefix} `)).map(([k, e]) => [k.slice(prefix.length + 1) || '(any)', e]);
  if (rows.length) out.push(table(title, rows, 'argument'));
}
out.push('### Used only by the harness host shims');
out.push('');
out.push('Not called from bundles. These are the reproduction of the VCockpit host (gauge loading, custom element registration) and belong to the runtime, not the DOM.');
out.push('');
out.push([...hostOnly.keys()].filter((k) => !bundleKeys.has(k)).sort().map((k) => `\`${k}\``).join(', ') || '(none)');
out.push('');
out.push('## CSS');
out.push('');
out.push(`Style sheets loaded: ${[...new Set(runs.flatMap((r) => r.data.css.sheets))].map((s) => `\`${s}\``).join(', ')}`);
out.push('');
out.push(table('Rule types', merge((d) => d.css.ruleTypes), 'rule'));
out.push(table('Properties in style sheet rules', merge((d) => d.css.sheetProps), 'property'));
out.push(table('Properties in @keyframes', merge((d) => d.css.keyframeProps), 'property'));
out.push(table('Value functions and flags in style sheets', merge((d) => d.css.valueFunctions), 'function'));
out.push(table('Selector features', merge((d) => d.css.selectorFeatures), 'feature'));
out.push(table('Inline style properties in the final document', merge((d) => d.css.inlineStyleProps), 'property'));
out.push(
  table(
    'Computed properties that take effect',
    merge((d) => d.css.computedNonInitial),
    'property',
    'Elements whose computed value differs from a bare element of the same tag: the properties a renderer must honour. `(elements with display: none)` counts hidden elements, which were skipped.',
  ),
);
out.push('## Elements and SVG features in the final document');
out.push('');
out.push(table('SVG elements', merge((d) => d.dom.svgElements), 'element'));
out.push(table('HTML elements', merge((d) => d.dom.htmlElements), 'element'));
out.push(table('Attributes by element', merge((d) => d.dom.attributes), 'namespace <element> attribute'));
out.push(table('Transform functions', merge((d) => d.dom.transformFunctions), 'function'));
out.push(table('Path data commands', merge((d) => d.dom.pathCommands), 'command'));

const target = path.join(DOCS_DIR, 'dom-usage-recorded.md');
fs.writeFileSync(target, out.join('\n'));
console.log(`${target}: ${runs.length} recordings (${states.length} states, ${screens.length} screens)`);
