// Copyright (c) 2023-2026 FlyByWire Simulations
// SPDX-License-Identifier: GPL-3.0

export interface DerivedFailureEntry {
  id: number;
  area: string;
  component: string;
  name: string;
}

export const DERIVED_FAILURE_TABLE: readonly DerivedFailureEntry[] = [
  { id: 24_020, area: 'electrical', component: '24_elec.vfg-1', name: 'Engine generator 1 failed' },
  { id: 24_021, area: 'electrical', component: '24_elec.vfg-2', name: 'Engine generator 2 failed' },
  { id: 24_022, area: 'electrical', component: '24_elec.vfg-3', name: 'Engine generator 3 failed' },
  { id: 24_023, area: 'electrical', component: '24_elec.vfg-4', name: 'Engine generator 4 failed' },
  { id: 24_030, area: 'electrical', component: '24_elec.apu-gen-1', name: 'APU generator 1 failed' },
  { id: 24_031, area: 'electrical', component: '24_elec.apu-gen-2', name: 'APU generator 2 failed' },
  { id: 24_000, area: 'electrical', component: '24_elec.tr-1', name: 'Transformer rectifier 1 failed' },
  { id: 24_001, area: 'electrical', component: '24_elec.tr-2', name: 'Transformer rectifier 2 failed' },
  { id: 24_002, area: 'electrical', component: '24_elec.tr-ess', name: 'Transformer rectifier ESS failed' },
  { id: 24_003, area: 'electrical', component: '24_elec.tr-apu', name: 'Transformer rectifier APU failed' },
  { id: 24_004, area: 'electrical', component: '24_elec.static-inv', name: 'Static inverter failed' },
  { id: 24_100, area: 'electrical', component: '24_elec.bus.AC1', name: 'AC1 bus failed' },
  { id: 24_101, area: 'electrical', component: '24_elec.bus.AC2', name: 'AC2 bus failed' },
  { id: 24_102, area: 'electrical', component: '24_elec.bus.AC3', name: 'AC3 bus failed' },
  { id: 24_103, area: 'electrical', component: '24_elec.bus.AC4', name: 'AC4 bus failed' },
  { id: 24_105, area: 'electrical', component: '24_elec.bus.AC_ESS', name: 'AC ESS bus failed' },
  { id: 24_104, area: 'electrical', component: '24_elec.bus.AC_EMER', name: 'AC EMER bus failed' },
  { id: 24_107, area: 'electrical', component: '24_elec.bus.AC_GND_FLT_SVC', name: 'AC GND/FLT SVC bus failed' },
  { id: 24_108, area: 'electrical', component: '24_elec.bus.DC1', name: 'DC1 bus failed' },
  { id: 24_109, area: 'electrical', component: '24_elec.bus.DC2', name: 'DC2 bus failed' },
  { id: 24_110, area: 'electrical', component: '24_elec.bus.DC_ESS', name: 'DC ESS bus failed' },
  { id: 24_113, area: 'electrical', component: '24_elec.bus.DC_HOT1', name: 'DC HOT1 bus failed' },
  { id: 24_114, area: 'electrical', component: '24_elec.bus.DC_HOT2', name: 'DC HOT2 bus failed' },
  { id: 24_112, area: 'electrical', component: '24_elec.bus.DC_APU', name: 'DC APU bus failed' },
  { id: 24_117, area: 'electrical', component: '24_elec.bus.DC_GND_FLT_SVC', name: 'DC GND/FLT SVC bus failed' },

  { id: 29_010, area: 'hydraulics', component: '29_hyd.green_edp_1a', name: 'Engine-driven pump 1A failed' },
  { id: 29_011, area: 'hydraulics', component: '29_hyd.green_edp_1b', name: 'Engine-driven pump 1B failed' },
  { id: 29_012, area: 'hydraulics', component: '29_hyd.green_edp_2a', name: 'Engine-driven pump 2A failed' },
  { id: 29_013, area: 'hydraulics', component: '29_hyd.green_edp_2b', name: 'Engine-driven pump 2B failed' },
  { id: 29_014, area: 'hydraulics', component: '29_hyd.yellow_edp_3a', name: 'Engine-driven pump 3A failed' },
  { id: 29_015, area: 'hydraulics', component: '29_hyd.yellow_edp_3b', name: 'Engine-driven pump 3B failed' },
  { id: 29_016, area: 'hydraulics', component: '29_hyd.yellow_edp_4a', name: 'Engine-driven pump 4A failed' },
  { id: 29_017, area: 'hydraulics', component: '29_hyd.yellow_edp_4b', name: 'Engine-driven pump 4B failed' },
  { id: 29_006, area: 'hydraulics', component: '29_hyd.green_electric_pump_a', name: 'Green electric pump A failed' },
  { id: 29_007, area: 'hydraulics', component: '29_hyd.green_electric_pump_b', name: 'Green electric pump B failed' },
  { id: 29_008, area: 'hydraulics', component: '29_hyd.yellow_electric_pump_a', name: 'Yellow electric pump A failed' },
  { id: 29_009, area: 'hydraulics', component: '29_hyd.yellow_electric_pump_b', name: 'Yellow electric pump B failed' },
  { id: 29_002, area: 'hydraulics', component: '29_hyd.green_reservoir', name: 'Green reservoir air pressurization lost' },
  { id: 29_003, area: 'hydraulics', component: '29_hyd.yellow_reservoir', name: 'Yellow reservoir air pressurization lost' },

  { id: 36_008, area: 'pneumatic_ducts', component: '36_pneu.engine_upstream_valve_stage', name: 'Engine 1 HP bleed valve stuck' },
  { id: 36_009, area: 'pneumatic_ducts', component: '36_pneu.engine_upstream_valve_stage', name: 'Engine 2 HP bleed valve stuck' },
  { id: 36_010, area: 'pneumatic_ducts', component: '36_pneu.engine_upstream_valve_stage', name: 'Engine 3 HP bleed valve stuck' },
  { id: 36_011, area: 'pneumatic_ducts', component: '36_pneu.engine_upstream_valve_stage', name: 'Engine 4 HP bleed valve stuck' },
  { id: 36_012, area: 'pneumatic_ducts', component: '36_pneu.engine_upstream_valve_stage', name: 'Engine 1 PR bleed valve stuck' },
  { id: 36_013, area: 'pneumatic_ducts', component: '36_pneu.engine_upstream_valve_stage', name: 'Engine 2 PR bleed valve stuck' },
  { id: 36_014, area: 'pneumatic_ducts', component: '36_pneu.engine_upstream_valve_stage', name: 'Engine 3 PR bleed valve stuck' },
  { id: 36_015, area: 'pneumatic_ducts', component: '36_pneu.engine_upstream_valve_stage', name: 'Engine 4 PR bleed valve stuck' },

  { id: 26_001, area: 'fire_ice', component: '26_fire.zone.engine1', name: 'Engine 1 zone on fire (SetOnFire)' },
  { id: 26_002, area: 'fire_ice', component: '26_fire.zone.engine2', name: 'Engine 2 zone on fire (SetOnFire)' },
  { id: 26_003, area: 'fire_ice', component: '26_fire.zone.engine3', name: 'Engine 3 zone on fire (SetOnFire)' },
  { id: 26_004, area: 'fire_ice', component: '26_fire.zone.engine4', name: 'Engine 4 zone on fire (SetOnFire)' },
  { id: 26_005, area: 'fire_ice', component: '26_fire.zone.apu', name: 'APU zone on fire (SetOnFire)' },
  { id: 26_006, area: 'fire_ice', component: '26_fire.zone.mlg', name: 'MLG bay zone on fire (SetOnFire)' },
  { id: 26_007, area: 'fire_ice', component: '26_fire.zone.engine1', name: 'Engine 1 fire loop A fault' },
  { id: 26_009, area: 'fire_ice', component: '26_fire.zone.engine2', name: 'Engine 2 fire loop A fault' },
  { id: 26_011, area: 'fire_ice', component: '26_fire.zone.engine3', name: 'Engine 3 fire loop A fault' },
  { id: 26_013, area: 'fire_ice', component: '26_fire.zone.engine4', name: 'Engine 4 fire loop A fault' },
  { id: 26_015, area: 'fire_ice', component: '26_fire.zone.apu', name: 'APU fire loop A fault' },
  { id: 26_017, area: 'fire_ice', component: '26_fire.zone.mlg', name: 'MLG bay fire loop A fault' },
  { id: 26_008, area: 'fire_ice', component: '26_fire.zone.engine1', name: 'Engine 1 fire loop B fault' },
  { id: 26_010, area: 'fire_ice', component: '26_fire.zone.engine2', name: 'Engine 2 fire loop B fault' },
  { id: 26_012, area: 'fire_ice', component: '26_fire.zone.engine3', name: 'Engine 3 fire loop B fault' },
  { id: 26_014, area: 'fire_ice', component: '26_fire.zone.engine4', name: 'Engine 4 fire loop B fault' },
  { id: 26_016, area: 'fire_ice', component: '26_fire.zone.apu', name: 'APU fire loop B fault' },
  { id: 26_018, area: 'fire_ice', component: '26_fire.zone.mlg', name: 'MLG bay fire loop B fault' },

  { id: 32_020, area: 'gear_structure', component: '32_gear.nose.retraction', name: 'Gear actuator jammed (Nose)' },
  { id: 32_021, area: 'gear_structure', component: '32_gear.left.retraction', name: 'Gear actuator jammed (Left)' },
  { id: 32_022, area: 'gear_structure', component: '32_gear.right.retraction', name: 'Gear actuator jammed (Right)' },
  { id: 32_023, area: 'gear_structure', component: '32_gear.nose.door', name: 'Gear door actuator jammed (Nose)' },
  { id: 32_024, area: 'gear_structure', component: '32_gear.left.door', name: 'Gear door actuator jammed (Left)' },
  { id: 32_025, area: 'gear_structure', component: '32_gear.right.door', name: 'Gear door actuator jammed (Right)' },
  { id: 32_004, area: 'gear_structure', component: '32_gear.nose.retraction', name: 'Gear prox sensor damage (Uplock Nose 1)' },
  { id: 32_005, area: 'gear_structure', component: '32_gear.nose.retraction', name: 'Gear prox sensor damage (Downlock Nose 2)' },
  { id: 32_006, area: 'gear_structure', component: '32_gear.right.retraction', name: 'Gear prox sensor damage (Uplock Right 1)' },
  { id: 32_007, area: 'gear_structure', component: '32_gear.right.retraction', name: 'Gear prox sensor damage (Downlock Right 2)' },
  { id: 32_008, area: 'gear_structure', component: '32_gear.left.retraction', name: 'Gear prox sensor damage (Uplock Left 2)' },
  { id: 32_009, area: 'gear_structure', component: '32_gear.left.retraction', name: 'Gear prox sensor damage (Downlock Left 1)' },
  { id: 32_030, area: 'gear_structure', component: '32_gear.parking_brake.accumulator', name: 'Brake accumulator gas leak' },

  { id: 34_000, area: 'sensors', component: '34_nav.ra_transceiver_1', name: 'Radio altimeter 1 failed' },
  { id: 34_001, area: 'sensors', component: '34_nav.ra_transceiver_2', name: 'Radio altimeter 2 failed' },
  { id: 34_002, area: 'sensors', component: '34_nav.ra_transceiver_3', name: 'Radio altimeter 3 failed' },
  { id: 34_010, area: 'sensors', component: '34_nav.ra_tx_antenna_1', name: 'Radio altimeter 1 antenna interrupted' },
  { id: 34_011, area: 'sensors', component: '34_nav.ra_tx_antenna_2', name: 'Radio altimeter 2 antenna interrupted' },
  { id: 34_012, area: 'sensors', component: '34_nav.ra_tx_antenna_3', name: 'Radio altimeter 3 antenna interrupted' },
];
