//! Exact mirrors of FlyByWire's A380 PRIM, SEC and FCU bus structs.
//!
//! GENERATED by src/fbw_cpp/gen_types.py from the Simulink headers
//! A380PrimComputerGeneralLogic_types.h, A380SecComputer_types.h and
//! A380FcuComputer_types.h. Do not edit; re-run the script instead.
//!
//! `boolean_T` is `u8`; Simulink `enum class ... : int32_T` fields are `i32`
//! (the enum's name is in the field comment). Every size, alignment and
//! field offset is asserted here and, with the same numbers, in
//! src/fbw_cpp/fbw_types_layout.h against g++'s layout.

#![allow(dead_code, non_snake_case, clippy::upper_case_acronyms)]

use std::mem::{align_of, offset_of, size_of};

pub use crate::fbw_controllers::{BaseArinc429, BaseEec, BasePrimFctlOutBus, BasePrimFeOutBus, BasePrimFgOutBus, BasePrimOutBus};

/// `base_time` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseTime {
    pub dt: f64,
    pub simulation_time: f64,
    pub monotonic_time: f64,
}

/// `base_sim_data` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseSimData {
    pub slew_on: u8,  // boolean_T (unsigned char)
    pub pause_on: u8,  // boolean_T (unsigned char)
    pub tracking_mode_on_override: u8,  // boolean_T (unsigned char)
    pub tailstrike_protection_on: u8,  // boolean_T (unsigned char)
    pub computer_running: u8,  // boolean_T (unsigned char)
}

/// `base_prim_sim_input` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BasePrimSimInput {
    pub spd_mach: f32,
    pub hdg_trk: f32,
    pub alt: f32,
    pub vs_fpa: f32,
}

/// `base_prim_discrete_inputs` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BasePrimDiscreteInputs {
    pub alignment_dummy: f64,
    pub prim_overhead_button_pressed: u8,  // boolean_T (unsigned char)
    pub is_unit_1: u8,  // boolean_T (unsigned char)
    pub is_unit_2: u8,  // boolean_T (unsigned char)
    pub is_unit_3: u8,  // boolean_T (unsigned char)
    pub capt_priority_takeover_pressed: u8,  // boolean_T (unsigned char)
    pub fo_priority_takeover_pressed: u8,  // boolean_T (unsigned char)
    pub ap_1_pushbutton_pressed: u8,  // boolean_T (unsigned char)
    pub ap_2_pushbutton_pressed: u8,  // boolean_T (unsigned char)
    pub fcu_1_healthy: u8,  // boolean_T (unsigned char)
    pub fcu_2_healthy: u8,  // boolean_T (unsigned char)
    pub athr_pushbutton: u8,  // boolean_T (unsigned char)
    pub ir_3_on_capt: u8,  // boolean_T (unsigned char)
    pub ir_3_on_fo: u8,  // boolean_T (unsigned char)
    pub adr_3_on_capt: u8,  // boolean_T (unsigned char)
    pub adr_3_on_fo: u8,  // boolean_T (unsigned char)
    pub rat_deployed: u8,  // boolean_T (unsigned char)
    pub rat_contactor_closed: u8,  // boolean_T (unsigned char)
    pub athr_instinctive_disc: u8,  // boolean_T (unsigned char)
    pub pitch_trim_up_pressed: u8,  // boolean_T (unsigned char)
    pub pitch_trim_down_pressed: u8,  // boolean_T (unsigned char)
    pub green_low_pressure: u8,  // boolean_T (unsigned char)
    pub yellow_low_pressure: u8,  // boolean_T (unsigned char)
}

/// `base_prim_analog_inputs` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BasePrimAnalogInputs {
    pub capt_pitch_stick_pos: f64,
    pub fo_pitch_stick_pos: f64,
    pub capt_roll_stick_pos: f64,
    pub fo_roll_stick_pos: f64,
    pub speed_brake_lever_pos: f64,
    pub thr_lever_1_pos: f64,
    pub thr_lever_2_pos: f64,
    pub thr_lever_3_pos: f64,
    pub thr_lever_4_pos: f64,
    pub elevator_1_pos_deg: f64,
    pub elevator_2_pos_deg: f64,
    pub elevator_3_pos_deg: f64,
    pub ths_pos_deg: f64,
    pub left_aileron_1_pos_deg: f64,
    pub left_aileron_2_pos_deg: f64,
    pub right_aileron_1_pos_deg: f64,
    pub right_aileron_2_pos_deg: f64,
    pub left_spoiler_pos_deg: f64,
    pub right_spoiler_pos_deg: f64,
    pub rudder_1_pos_deg: f64,
    pub rudder_2_pos_deg: f64,
    pub rudder_pedal_pos: f64,
    pub yellow_hyd_pressure_psi: f64,
    pub green_hyd_pressure_psi: f64,
    pub vert_acc_1_g: f64,
    pub vert_acc_2_g: f64,
    pub vert_acc_3_g: f64,
    pub lat_acc_1_g: f64,
    pub lat_acc_2_g: f64,
    pub lat_acc_3_g: f64,
    pub left_body_wheel_speed: f64,
    pub left_wing_wheel_speed: f64,
    pub right_body_wheel_speed: f64,
    pub right_wing_wheel_speed: f64,
}

/// `base_adr_bus` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseAdrBus {
    pub altitude_standard_ft: BaseArinc429,
    pub altitude_corrected_1_ft: BaseArinc429,
    pub altitude_corrected_2_ft: BaseArinc429,
    pub mach: BaseArinc429,
    pub airspeed_computed_kn: BaseArinc429,
    pub airspeed_true_kn: BaseArinc429,
    pub vertical_speed_ft_min: BaseArinc429,
    pub aoa_corrected_deg: BaseArinc429,
    pub corrected_average_static_pressure: BaseArinc429,
}

/// `base_ir_bus` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseIrBus {
    pub discrete_word_1: BaseArinc429,
    pub latitude_deg: BaseArinc429,
    pub longitude_deg: BaseArinc429,
    pub ground_speed_kn: BaseArinc429,
    pub track_angle_true_deg: BaseArinc429,
    pub heading_true_deg: BaseArinc429,
    pub wind_speed_kn: BaseArinc429,
    pub wind_direction_true_deg: BaseArinc429,
    pub track_angle_magnetic_deg: BaseArinc429,
    pub heading_magnetic_deg: BaseArinc429,
    pub drift_angle_deg: BaseArinc429,
    pub flight_path_angle_deg: BaseArinc429,
    pub flight_path_accel_g: BaseArinc429,
    pub pitch_angle_deg: BaseArinc429,
    pub roll_angle_deg: BaseArinc429,
    pub body_pitch_rate_deg_s: BaseArinc429,
    pub body_roll_rate_deg_s: BaseArinc429,
    pub body_yaw_rate_deg_s: BaseArinc429,
    pub body_long_accel_g: BaseArinc429,
    pub body_lat_accel_g: BaseArinc429,
    pub body_normal_accel_g: BaseArinc429,
    pub track_angle_rate_deg_s: BaseArinc429,
    pub pitch_att_rate_deg_s: BaseArinc429,
    pub roll_att_rate_deg_s: BaseArinc429,
    pub inertial_alt_ft: BaseArinc429,
    pub along_track_horiz_acc_g: BaseArinc429,
    pub cross_track_horiz_acc_g: BaseArinc429,
    pub vertical_accel_g: BaseArinc429,
    pub inertial_vertical_speed_ft_s: BaseArinc429,
    pub north_south_velocity_kn: BaseArinc429,
    pub east_west_velocity_kn: BaseArinc429,
}

/// `base_ra_bus` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseRaBus {
    pub radio_height_ft: BaseArinc429,
}

/// `base_ils_bus` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseIlsBus {
    pub runway_heading_deg: BaseArinc429,
    pub ils_frequency_mhz: BaseArinc429,
    pub localizer_deviation_deg: BaseArinc429,
    pub glideslope_deviation_deg: BaseArinc429,
}

/// `base_sfcc_bus` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseSfccBus {
    pub slat_flap_component_status_word: BaseArinc429,
    pub slat_flap_system_status_word: BaseArinc429,
    pub slat_flap_actual_position_word: BaseArinc429,
    pub slat_actual_position_deg: BaseArinc429,
    pub flap_actual_position_deg: BaseArinc429,
}

/// `base_lgciu_bus` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseLgciuBus {
    pub discrete_word_1: BaseArinc429,
    pub discrete_word_2: BaseArinc429,
    pub discrete_word_3: BaseArinc429,
    pub discrete_word_4: BaseArinc429,
}

/// `base_fcu_bus` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseFcuBus {
    pub efis_discrete_word_1: BaseArinc429,
    pub efis_discrete_word_2: BaseArinc429,
    pub baro_setting_hpa: BaseArinc429,
    pub baro_setting_inhg: BaseArinc429,
    pub afs_discrete_word_1: BaseArinc429,
    pub afs_discrete_word_2: BaseArinc429,
}

/// `base_sec_out_bus` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseSecOutBus {
    pub left_sidestick_pitch_command_deg: BaseArinc429,
    pub right_sidestick_pitch_command_deg: BaseArinc429,
    pub left_sidestick_roll_command_deg: BaseArinc429,
    pub right_sidestick_roll_command_deg: BaseArinc429,
    pub rudder_pedal_position_deg: BaseArinc429,
    pub aileron_status_word: BaseArinc429,
    pub left_aileron_1_position_deg: BaseArinc429,
    pub left_aileron_2_position_deg: BaseArinc429,
    pub right_aileron_1_position_deg: BaseArinc429,
    pub right_aileron_2_position_deg: BaseArinc429,
    pub spoiler_status_word: BaseArinc429,
    pub left_spoiler_1_position_deg: BaseArinc429,
    pub right_spoiler_1_position_deg: BaseArinc429,
    pub left_spoiler_2_position_deg: BaseArinc429,
    pub right_spoiler_2_position_deg: BaseArinc429,
    pub elevator_status_word: BaseArinc429,
    pub elevator_1_position_deg: BaseArinc429,
    pub elevator_2_position_deg: BaseArinc429,
    pub elevator_3_position_deg: BaseArinc429,
    pub ths_position_deg: BaseArinc429,
    pub rudder_status_word: BaseArinc429,
    pub rudder_1_position_deg: BaseArinc429,
    pub rudder_2_position_deg: BaseArinc429,
    pub rudder_trim_actual_pos_deg: BaseArinc429,
    pub fctl_law_status_word: BaseArinc429,
    pub misc_data_status_word: BaseArinc429,
}

/// `base_prim_bus_inputs` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BasePrimBusInputs {
    pub adr_1_bus: BaseAdrBus,
    pub adr_2_bus: BaseAdrBus,
    pub adr_3_bus: BaseAdrBus,
    pub ir_1_bus: BaseIrBus,
    pub ir_2_bus: BaseIrBus,
    pub ir_3_bus: BaseIrBus,
    pub isis_1_bus: f64,
    pub isis_2_bus: f64,
    pub rate_gyro_pitch_1_bus: f64,
    pub rate_gyro_pitch_2_bus: f64,
    pub rate_gyro_roll_1_bus: f64,
    pub rate_gyro_roll_2_bus: f64,
    pub rate_gyro_yaw_1_bus: f64,
    pub rate_gyro_yaw_2_bus: f64,
    pub ra_1_bus: BaseRaBus,
    pub ra_2_bus: BaseRaBus,
    pub ils_1_bus: BaseIlsBus,
    pub ils_2_bus: BaseIlsBus,
    pub sfcc_1_bus: BaseSfccBus,
    pub sfcc_2_bus: BaseSfccBus,
    pub lgciu_1_bus: BaseLgciuBus,
    pub lgciu_2_bus: BaseLgciuBus,
    pub irdc_1_bus: f64,
    pub irdc_2_bus: f64,
    pub irdc_3_bus: f64,
    pub irdc_4_a_bus: f64,
    pub irdc_4_b_bus: f64,
    pub fcu_1_bus: BaseFcuBus,
    pub fcu_2_bus: BaseFcuBus,
    pub prim_x_bus: BasePrimOutBus,
    pub prim_y_bus: BasePrimOutBus,
    pub sec_1_bus: BaseSecOutBus,
    pub sec_2_bus: BaseSecOutBus,
    pub sec_3_bus: BaseSecOutBus,
}

/// `base_fms_inputs` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseFmsInputs {
    pub fm_valid: u8,  // boolean_T (unsigned char)
    pub active_fms_flight_phase: i32,  // fms_flight_phase (enum class : int32_T)
    pub selected_approach_type: i32,  // fmgc_approach_type (enum class : int32_T)
    pub backbeam_selected: u8,  // boolean_T (unsigned char)
    pub fms_loc_distance: f64,
    pub fms_unrealistic_gs_angle_deg: f64,
    pub lateral_flight_plan_valid: u8,  // boolean_T (unsigned char)
    pub nav_capture_condition: u8,  // boolean_T (unsigned char)
    pub phi_c_deg: f64,
    pub xtk_nmi: f64,
    pub tke_deg: f64,
    pub phi_limit_deg: f64,
    pub direct_to_nav_engage: u8,  // boolean_T (unsigned char)
    pub vertical_flight_plan_valid: u8,  // boolean_T (unsigned char)
    pub final_app_can_engage: u8,  // boolean_T (unsigned char)
    pub next_alt_cstr_ft: f64,
    pub requested_des_submode: i32,  // fmgc_des_submode (enum class : int32_T)
    pub alt_profile_tgt_ft: f64,
    pub vs_target_ft_min: f64,
    pub v_2_kts: f64,
    pub v_app_kts: f64,
    pub v_managed_kts: f64,
    pub v_upper_margin_kts: f64,
    pub v_lower_margin_kts: f64,
    pub show_speed_margins: u8,  // boolean_T (unsigned char)
    pub preset_spd_kts: f64,
    pub preset_mach: f64,
    pub preset_spd_mach_activate: u8,  // boolean_T (unsigned char)
    pub fms_spd_mode_activate: u8,  // boolean_T (unsigned char)
    pub fms_mach_mode_activate: u8,  // boolean_T (unsigned char)
    pub flex_temp_deg_c: f64,
    pub acceleration_alt_ft: f64,
    pub thrust_reduction_alt_ft: f64,
    pub cruise_alt_ft: f64,
    pub tower_headwind_kn: BaseArinc429,
    pub flap_3_approach_selected: u8,  // boolean_T (unsigned char)
}

/// `base_fqms` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseFqms {
    pub gross_weight_kg: BaseArinc429,
    pub gross_weight_cg_pct: BaseArinc429,
}

/// `base_tcas` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseTcas {
    pub tcas_valid: u8,  // boolean_T (unsigned char)
    pub ta_ra_mode: u8,  // boolean_T (unsigned char)
    pub ta_active: u8,  // boolean_T (unsigned char)
    pub ra_active: u8,  // boolean_T (unsigned char)
    pub ra_rate_to_maintain: f64,
    pub ra_corrective: u8,  // boolean_T (unsigned char)
}

/// `base_prim_adcn_inputs` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BasePrimAdcnInputs {
    pub fms: BaseFmsInputs,
    pub fqms: BaseFqms,
    pub eec_1: BaseEec,
    pub eec_2: BaseEec,
    pub eec_3: BaseEec,
    pub eec_4: BaseEec,
    pub tcas: BaseTcas,
}

/// `prim_inputs` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct PrimInputs {
    pub time: BaseTime,
    pub sim_data: BaseSimData,
    pub sim_input: BasePrimSimInput,
    pub discrete_inputs: BasePrimDiscreteInputs,
    pub analog_inputs: BasePrimAnalogInputs,
    pub bus_inputs: BasePrimBusInputs,
    pub adcn_inputs: BasePrimAdcnInputs,
}

/// `base_prim_discrete_outputs` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BasePrimDiscreteOutputs {
    pub alignment_dummy: f64,
    pub elevator_1_active_mode: u8,  // boolean_T (unsigned char)
    pub elevator_2_active_mode: u8,  // boolean_T (unsigned char)
    pub elevator_3_active_mode: u8,  // boolean_T (unsigned char)
    pub ths_active_mode: u8,  // boolean_T (unsigned char)
    pub left_aileron_1_active_mode: u8,  // boolean_T (unsigned char)
    pub left_aileron_2_active_mode: u8,  // boolean_T (unsigned char)
    pub right_aileron_1_active_mode: u8,  // boolean_T (unsigned char)
    pub right_aileron_2_active_mode: u8,  // boolean_T (unsigned char)
    pub left_spoiler_electronic_module_enable: u8,  // boolean_T (unsigned char)
    pub right_spoiler_electronic_module_enable: u8,  // boolean_T (unsigned char)
    pub rudder_1_hydraulic_active_mode: u8,  // boolean_T (unsigned char)
    pub rudder_1_electric_active_mode: u8,  // boolean_T (unsigned char)
    pub rudder_2_hydraulic_active_mode: u8,  // boolean_T (unsigned char)
    pub rudder_2_electric_active_mode: u8,  // boolean_T (unsigned char)
    pub prim_healthy: u8,  // boolean_T (unsigned char)
    pub fcu_1_select: u8,  // boolean_T (unsigned char)
    pub fcu_2_select: u8,  // boolean_T (unsigned char)
    pub ap_engaged: u8,  // boolean_T (unsigned char)
    pub reverser_tertiary_lock: u8,  // boolean_T (unsigned char)
}

/// `base_prim_analog_outputs` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BasePrimAnalogOutputs {
    pub elevator_1_pos_order_deg: f64,
    pub elevator_2_pos_order_deg: f64,
    pub elevator_3_pos_order_deg: f64,
    pub ths_pos_order_deg: f64,
    pub left_aileron_1_pos_order_deg: f64,
    pub left_aileron_2_pos_order_deg: f64,
    pub right_aileron_1_pos_order_deg: f64,
    pub right_aileron_2_pos_order_deg: f64,
    pub left_spoiler_pos_order_deg: f64,
    pub right_spoiler_pos_order_deg: f64,
    pub rudder_1_pos_order_deg: f64,
    pub rudder_2_pos_order_deg: f64,
}

/// `ap_raw_laws_flare` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct ApRawLawsFlare {
    pub condition_Flare: u8,  // boolean_T (unsigned char)
    pub H_dot_radio_fpm: f64,
    pub H_dot_c_fpm: f64,
    pub delta_Theta_H_dot_deg: f64,
    pub delta_Theta_bz_deg: f64,
    pub delta_Theta_bx_deg: f64,
    pub delta_Theta_beta_c_deg: f64,
}

/// `base_prim_surface_status` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BasePrimSurfaceStatus {
    pub left_inboard_aileron_engaged: u8,  // boolean_T (unsigned char)
    pub right_inboard_aileron_engaged: u8,  // boolean_T (unsigned char)
    pub left_midboard_aileron_engaged: u8,  // boolean_T (unsigned char)
    pub right_midboard_aileron_engaged: u8,  // boolean_T (unsigned char)
    pub left_outboard_aileron_engaged: u8,  // boolean_T (unsigned char)
    pub right_outboard_aileron_engaged: u8,  // boolean_T (unsigned char)
    pub spoiler_pair_1_engaged: u8,  // boolean_T (unsigned char)
    pub spoiler_pair_2_engaged: u8,  // boolean_T (unsigned char)
    pub spoiler_pair_3_engaged: u8,  // boolean_T (unsigned char)
    pub spoiler_pair_4_engaged: u8,  // boolean_T (unsigned char)
    pub spoiler_pair_5_engaged: u8,  // boolean_T (unsigned char)
    pub spoiler_pair_6_engaged: u8,  // boolean_T (unsigned char)
    pub spoiler_pair_7_engaged: u8,  // boolean_T (unsigned char)
    pub spoiler_pair_8_engaged: u8,  // boolean_T (unsigned char)
    pub left_inboard_elevator_engaged: u8,  // boolean_T (unsigned char)
    pub right_inboard_elevator_engaged: u8,  // boolean_T (unsigned char)
    pub left_outboard_elevator_engaged: u8,  // boolean_T (unsigned char)
    pub right_outboard_elevator_engaged: u8,  // boolean_T (unsigned char)
    pub ths_engaged: u8,  // boolean_T (unsigned char)
    pub upper_rudder_engaged: u8,  // boolean_T (unsigned char)
    pub lower_rudder_engaged: u8,  // boolean_T (unsigned char)
}

/// `base_prim_lateral_surface_positions` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BasePrimLateralSurfacePositions {
    pub left_inboard_aileron_deg: f64,
    pub right_inboard_aileron_deg: f64,
    pub left_midboard_aileron_deg: f64,
    pub right_midboard_aileron_deg: f64,
    pub left_outboard_aileron_deg: f64,
    pub right_outboard_aileron_deg: f64,
    pub left_spoiler_1_deg: f64,
    pub right_spoiler_1_deg: f64,
    pub left_spoiler_2_deg: f64,
    pub right_spoiler_2_deg: f64,
    pub left_spoiler_3_deg: f64,
    pub right_spoiler_3_deg: f64,
    pub left_spoiler_4_deg: f64,
    pub right_spoiler_4_deg: f64,
    pub left_spoiler_5_deg: f64,
    pub right_spoiler_5_deg: f64,
    pub left_spoiler_6_deg: f64,
    pub right_spoiler_6_deg: f64,
    pub left_spoiler_7_deg: f64,
    pub right_spoiler_7_deg: f64,
    pub left_spoiler_8_deg: f64,
    pub right_spoiler_8_deg: f64,
    pub upper_rudder_deg: f64,
    pub lower_rudder_deg: f64,
}

/// `base_prim_pitch_surface_positions` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BasePrimPitchSurfacePositions {
    pub left_inboard_elevator_deg: f64,
    pub right_inboard_elevator_deg: f64,
    pub left_outboard_elevator_deg: f64,
    pub right_outboard_elevator_deg: f64,
    pub ths_deg: f64,
}

/// `base_prim_fctl_logic_outputs` in A380PrimComputerGeneralLogic_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BasePrimFctlLogicOutputs {
    pub surface_statuses: BasePrimSurfaceStatus,
    pub lateral_surface_positions: BasePrimLateralSurfacePositions,
    pub pitch_surface_positions: BasePrimPitchSurfacePositions,
    pub lateral_law_capability: i32,  // a380_lateral_efcs_law (enum class : int32_T)
    pub active_lateral_law: i32,  // a380_lateral_efcs_law (enum class : int32_T)
    pub pitch_law_capability: i32,  // a380_pitch_efcs_law (enum class : int32_T)
    pub active_pitch_law: i32,  // a380_pitch_efcs_law (enum class : int32_T)
    pub abnormal_condition_law_active: u8,  // boolean_T (unsigned char)
    pub is_master_prim: u8,  // boolean_T (unsigned char)
    pub elevator_1_avail: u8,  // boolean_T (unsigned char)
    pub elevator_1_engaged: u8,  // boolean_T (unsigned char)
    pub elevator_2_avail: u8,  // boolean_T (unsigned char)
    pub elevator_2_engaged: u8,  // boolean_T (unsigned char)
    pub elevator_3_avail: u8,  // boolean_T (unsigned char)
    pub elevator_3_engaged: u8,  // boolean_T (unsigned char)
    pub ths_avail: u8,  // boolean_T (unsigned char)
    pub ths_engaged: u8,  // boolean_T (unsigned char)
    pub left_aileron_1_avail: u8,  // boolean_T (unsigned char)
    pub left_aileron_1_engaged: u8,  // boolean_T (unsigned char)
    pub left_aileron_2_avail: u8,  // boolean_T (unsigned char)
    pub left_aileron_2_engaged: u8,  // boolean_T (unsigned char)
    pub right_aileron_1_avail: u8,  // boolean_T (unsigned char)
    pub right_aileron_1_engaged: u8,  // boolean_T (unsigned char)
    pub right_aileron_2_avail: u8,  // boolean_T (unsigned char)
    pub right_aileron_2_engaged: u8,  // boolean_T (unsigned char)
    pub left_spoiler_hydraulic_mode_avail: u8,  // boolean_T (unsigned char)
    pub left_spoiler_electric_mode_avail: u8,  // boolean_T (unsigned char)
    pub left_spoiler_hydraulic_mode_engaged: u8,  // boolean_T (unsigned char)
    pub left_spoiler_electric_mode_engaged: u8,  // boolean_T (unsigned char)
    pub right_spoiler_hydraulic_mode_avail: u8,  // boolean_T (unsigned char)
    pub right_spoiler_electric_mode_avail: u8,  // boolean_T (unsigned char)
    pub right_spoiler_hydraulic_mode_engaged: u8,  // boolean_T (unsigned char)
    pub right_spoiler_electric_mode_engaged: u8,  // boolean_T (unsigned char)
    pub rudder_1_hydraulic_mode_avail: u8,  // boolean_T (unsigned char)
    pub rudder_1_electric_mode_avail: u8,  // boolean_T (unsigned char)
    pub rudder_1_hydraulic_mode_engaged: u8,  // boolean_T (unsigned char)
    pub rudder_1_electric_mode_engaged: u8,  // boolean_T (unsigned char)
    pub rudder_2_hydraulic_mode_avail: u8,  // boolean_T (unsigned char)
    pub rudder_2_electric_mode_avail: u8,  // boolean_T (unsigned char)
    pub rudder_2_hydraulic_mode_engaged: u8,  // boolean_T (unsigned char)
    pub rudder_2_electric_mode_engaged: u8,  // boolean_T (unsigned char)
    pub aileron_droop_active: u8,  // boolean_T (unsigned char)
    pub aileron_antidroop_active: u8,  // boolean_T (unsigned char)
    pub ths_automatic_mode_active: u8,  // boolean_T (unsigned char)
    pub ths_manual_mode_c_deg_s: f64,
    pub eha_ebha_elec_mode_inhibited: u8,  // boolean_T (unsigned char)
    pub left_sidestick_disabled: u8,  // boolean_T (unsigned char)
    pub right_sidestick_disabled: u8,  // boolean_T (unsigned char)
    pub left_sidestick_priority_locked: u8,  // boolean_T (unsigned char)
    pub right_sidestick_priority_locked: u8,  // boolean_T (unsigned char)
    pub total_sidestick_pitch_command: f64,
    pub total_sidestick_roll_command: f64,
    pub speed_brake_inhibited: u8,  // boolean_T (unsigned char)
    pub speed_brake_command_deg: f64,
    pub ground_spoilers_armed: u8,  // boolean_T (unsigned char)
    pub ground_spoilers_out: u8,  // boolean_T (unsigned char)
    pub phased_lift_dumping_active: u8,  // boolean_T (unsigned char)
    pub ground_spoiler_command_deg: f64,
    pub spoiler_lift_active: u8,  // boolean_T (unsigned char)
    pub ap_authorised: u8,  // boolean_T (unsigned char)
    pub protection_ap_disconnect: u8,  // boolean_T (unsigned char)
    pub high_alpha_prot_active: u8,  // boolean_T (unsigned char)
    pub alpha_prot_deg: f64,
    pub alpha_max_deg: f64,
    pub v_alpha_prot_kn: f64,
    pub v_alpha_max_kn: f64,
    pub v_alpha_stall_warn_kn: f64,
    pub high_speed_prot_active: u8,  // boolean_T (unsigned char)
    pub high_speed_prot_lo_thresh_kn: f64,
    pub high_speed_prot_hi_thresh_kn: f64,
}

/// `base_sec_discrete_inputs` in A380SecComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseSecDiscreteInputs {
    pub sec_overhead_button_pressed: u8,  // boolean_T (unsigned char)
    pub is_unit_1: u8,  // boolean_T (unsigned char)
    pub is_unit_2: u8,  // boolean_T (unsigned char)
    pub is_unit_3: u8,  // boolean_T (unsigned char)
    pub capt_priority_takeover_pressed: u8,  // boolean_T (unsigned char)
    pub fo_priority_takeover_pressed: u8,  // boolean_T (unsigned char)
    pub rudder_trim_left_pressed: u8,  // boolean_T (unsigned char)
    pub rudder_trim_right_pressed: u8,  // boolean_T (unsigned char)
    pub rudder_trim_reset_pressed: u8,  // boolean_T (unsigned char)
    pub pitch_trim_up_pressed: u8,  // boolean_T (unsigned char)
    pub pitch_trim_down_pressed: u8,  // boolean_T (unsigned char)
    pub rat_deployed: u8,  // boolean_T (unsigned char)
    pub rat_contactor_closed: u8,  // boolean_T (unsigned char)
    pub green_low_pressure: u8,  // boolean_T (unsigned char)
    pub yellow_low_pressure: u8,  // boolean_T (unsigned char)
}

/// `base_sec_analog_inputs` in A380SecComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseSecAnalogInputs {
    pub capt_pitch_stick_pos: f64,
    pub fo_pitch_stick_pos: f64,
    pub capt_roll_stick_pos: f64,
    pub fo_roll_stick_pos: f64,
    pub elevator_1_pos_deg: f64,
    pub elevator_2_pos_deg: f64,
    pub elevator_3_pos_deg: f64,
    pub ths_pos_deg: f64,
    pub left_aileron_1_pos_deg: f64,
    pub left_aileron_2_pos_deg: f64,
    pub right_aileron_1_pos_deg: f64,
    pub right_aileron_2_pos_deg: f64,
    pub left_spoiler_1_pos_deg: f64,
    pub right_spoiler_1_pos_deg: f64,
    pub left_spoiler_2_pos_deg: f64,
    pub right_spoiler_2_pos_deg: f64,
    pub rudder_1_pos_deg: f64,
    pub rudder_2_pos_deg: f64,
    pub rudder_pedal_pos_deg: f64,
    pub rudder_trim_actual_pos_deg: f64,
}

/// `base_sec_bus_inputs` in A380SecComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseSecBusInputs {
    pub adr_1_bus: BaseAdrBus,
    pub adr_2_bus: BaseAdrBus,
    pub ir_1_bus: BaseIrBus,
    pub ir_2_bus: BaseIrBus,
    pub sfcc_1_bus: BaseSfccBus,
    pub sfcc_2_bus: BaseSfccBus,
    pub lgciu_1_bus: BaseLgciuBus,
    pub lgciu_2_bus: BaseLgciuBus,
    pub irdc_5_a_bus: f64,
    pub irdc_5_b_bus: f64,
    pub prim_1_bus: BasePrimOutBus,
    pub prim_2_bus: BasePrimOutBus,
    pub prim_3_bus: BasePrimOutBus,
    pub sec_x_bus: BaseSecOutBus,
    pub sec_y_bus: BaseSecOutBus,
}

/// `base_sec_adcn_inputs` in A380SecComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseSecAdcnInputs {
    pub eec_1: BaseEec,
    pub eec_2: BaseEec,
    pub eec_3: BaseEec,
    pub eec_4: BaseEec,
}

/// `sec_inputs` in A380SecComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct SecInputs {
    pub time: BaseTime,
    pub sim_data: BaseSimData,
    pub discrete_inputs: BaseSecDiscreteInputs,
    pub analog_inputs: BaseSecAnalogInputs,
    pub bus_inputs: BaseSecBusInputs,
    pub adcn_inputs: BaseSecAdcnInputs,
}

/// `base_sec_discrete_outputs` in A380SecComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseSecDiscreteOutputs {
    pub elevator_1_active_mode: u8,  // boolean_T (unsigned char)
    pub elevator_2_active_mode: u8,  // boolean_T (unsigned char)
    pub elevator_3_active_mode: u8,  // boolean_T (unsigned char)
    pub ths_active_mode: u8,  // boolean_T (unsigned char)
    pub left_aileron_1_active_mode: u8,  // boolean_T (unsigned char)
    pub left_aileron_2_active_mode: u8,  // boolean_T (unsigned char)
    pub right_aileron_1_active_mode: u8,  // boolean_T (unsigned char)
    pub right_aileron_2_active_mode: u8,  // boolean_T (unsigned char)
    pub rudder_1_hydraulic_active_mode: u8,  // boolean_T (unsigned char)
    pub rudder_1_electric_active_mode: u8,  // boolean_T (unsigned char)
    pub rudder_2_hydraulic_active_mode: u8,  // boolean_T (unsigned char)
    pub rudder_2_electric_active_mode: u8,  // boolean_T (unsigned char)
    pub rudder_trim_active_mode: u8,  // boolean_T (unsigned char)
    pub sec_healthy: u8,  // boolean_T (unsigned char)
}

/// `base_sec_analog_outputs` in A380SecComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseSecAnalogOutputs {
    pub elevator_1_pos_order_deg: f64,
    pub elevator_2_pos_order_deg: f64,
    pub elevator_3_pos_order_deg: f64,
    pub ths_pos_order_deg: f64,
    pub left_aileron_1_pos_order_deg: f64,
    pub left_aileron_2_pos_order_deg: f64,
    pub right_aileron_1_pos_order_deg: f64,
    pub right_aileron_2_pos_order_deg: f64,
    pub left_spoiler_1_pos_order_deg: f64,
    pub right_spoiler_1_pos_order_deg: f64,
    pub left_spoiler_2_pos_order_deg: f64,
    pub right_spoiler_2_pos_order_deg: f64,
    pub rudder_1_pos_order_deg: f64,
    pub rudder_2_pos_order_deg: f64,
    pub rudder_trim_command_deg: f64,
}

/// `base_fcu_sim_input` in A380FcuComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseFcuSimInput {
    pub baro_setting_hpa: f32,
    pub efis_mode: i8,
    pub efis_range: i8,
    pub navaid_1_mode: i8,
    pub navaid_2_mode: i8,
}

/// `base_fcu_knob_inputs` in A380FcuComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseFcuKnobInputs {
    pub pushed: u8,  // boolean_T (unsigned char)
    pub pulled: u8,  // boolean_T (unsigned char)
    pub turns: i8,
}

/// `base_fcu_efis_panel_inputs` in A380FcuComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseFcuEfisPanelInputs {
    pub efis_range_knob_turns: i8,
    pub efis_mode_knob_turns: i8,
    pub baro_is_inhg: u8,  // boolean_T (unsigned char)
    pub baro_knob: BaseFcuKnobInputs,
    pub vv_button_pushed: u8,  // boolean_T (unsigned char)
    pub ls_button_pushed: u8,  // boolean_T (unsigned char)
    pub taxi_button_pushed: u8,  // boolean_T (unsigned char)
    pub cstr_button_pushed: u8,  // boolean_T (unsigned char)
    pub wpt_button_pushed: u8,  // boolean_T (unsigned char)
    pub vord_button_pushed: u8,  // boolean_T (unsigned char)
    pub ndb_button_pushed: u8,  // boolean_T (unsigned char)
    pub arpt_button_pushed: u8,  // boolean_T (unsigned char)
    pub navaid_1_button_pushed: u8,  // boolean_T (unsigned char)
    pub navaid_2_button_pushed: u8,  // boolean_T (unsigned char)
    pub wx_button_pushed: u8,  // boolean_T (unsigned char)
    pub terr_button_pushed: u8,  // boolean_T (unsigned char)
    pub traf_button_pushed: u8,  // boolean_T (unsigned char)
}

/// `base_fcu_afs_panel_inputs` in A380FcuComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseFcuAfsPanelInputs {
    pub fd_button_pressed: u8,  // boolean_T (unsigned char)
    pub loc_button_pressed: u8,  // boolean_T (unsigned char)
    pub alt_button_pressed: u8,  // boolean_T (unsigned char)
    pub appr_button_pressed: u8,  // boolean_T (unsigned char)
    pub spd_mach_button_pressed: u8,  // boolean_T (unsigned char)
    pub true_mag_button_pressed: u8,  // boolean_T (unsigned char)
    pub trk_fpa_button_pressed: u8,  // boolean_T (unsigned char)
    pub metric_alt_button_pressed: u8,  // boolean_T (unsigned char)
    pub spd_knob: BaseFcuKnobInputs,
    pub hdg_trk_knob: BaseFcuKnobInputs,
    pub alt_knob: BaseFcuKnobInputs,
    pub alt_increment_1000: u8,  // boolean_T (unsigned char)
    pub vs_fpa_knob: BaseFcuKnobInputs,
}

/// `base_fcu_discrete_inputs` in A380FcuComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseFcuDiscreteInputs {
    pub fcu_switched_off: u8,  // boolean_T (unsigned char)
    pub efis_backup_activated: u8,  // boolean_T (unsigned char)
    pub selected_by_prim_1: u8,  // boolean_T (unsigned char)
    pub selected_by_prim_2: u8,  // boolean_T (unsigned char)
    pub selected_by_prim_3: u8,  // boolean_T (unsigned char)
    pub lights_test: u8,  // boolean_T (unsigned char)
    pub pin_prog_qfe_avail: u8,  // boolean_T (unsigned char)
    pub efis_inputs: BaseFcuEfisPanelInputs,
    pub afs_inputs: BaseFcuAfsPanelInputs,
}

/// `base_aesu_bus` in A380FcuComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseAesuBus {
    pub aesu_status_word: BaseArinc429,
}

/// `base_fcu_bus_inputs` in A380FcuComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseFcuBusInputs {
    pub prim_1_bus: BasePrimOutBus,
    pub prim_2_bus: BasePrimOutBus,
    pub prim_3_bus: BasePrimOutBus,
    pub aesu_bus: BaseAesuBus,
}

/// `fcu_inputs` in A380FcuComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct FcuInputs {
    pub time: BaseTime,
    pub sim_data: BaseSimData,
    pub sim_input: BaseFcuSimInput,
    pub discrete_inputs: BaseFcuDiscreteInputs,
    pub bus_inputs: BaseFcuBusInputs,
}

/// `base_fcu_efis_panel_outputs` in A380FcuComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseFcuEfisPanelOutputs {
    pub vv_light_on: u8,  // boolean_T (unsigned char)
    pub ls_light_on: u8,  // boolean_T (unsigned char)
    pub taxi_light_on: u8,  // boolean_T (unsigned char)
    pub cstr_light_on: u8,  // boolean_T (unsigned char)
    pub wpt_light_on: u8,  // boolean_T (unsigned char)
    pub vord_light_on: u8,  // boolean_T (unsigned char)
    pub ndb_light_on: u8,  // boolean_T (unsigned char)
    pub arpt_light_on: u8,  // boolean_T (unsigned char)
    pub traf_light_on: u8,  // boolean_T (unsigned char)
    pub wxr_light_on: u8,  // boolean_T (unsigned char)
    pub terr_light_on: u8,  // boolean_T (unsigned char)
    pub navaid_1_mode: i32,  // a380_efis_navaid_selection (enum class : int32_T)
    pub navaid_2_mode: i32,  // a380_efis_navaid_selection (enum class : int32_T)
    pub efis_range: i32,  // a380_efis_panel_range_selection (enum class : int32_T)
    pub efis_mode: i32,  // a380_efis_panel_mode_selection (enum class : int32_T)
    pub baro_is_inhg: u8,  // boolean_T (unsigned char)
    pub baro_is_std: u8,  // boolean_T (unsigned char)
    pub baro_value: f32,
    pub baro_mode: i8,
    pub baro_preset_visible: u8,  // boolean_T (unsigned char)
    pub efis_cp_active: u8,  // boolean_T (unsigned char)
}

/// `base_fcu_afs_panel_outputs` in A380FcuComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseFcuAfsPanelOutputs {
    pub loc_light_on: u8,  // boolean_T (unsigned char)
    pub alt_light_on: u8,  // boolean_T (unsigned char)
    pub appr_light_on: u8,  // boolean_T (unsigned char)
    pub ap_1_light_on: u8,  // boolean_T (unsigned char)
    pub ap_2_light_on: u8,  // boolean_T (unsigned char)
    pub athr_light_on: u8,  // boolean_T (unsigned char)
    pub fd_light_on: u8,  // boolean_T (unsigned char)
    pub trk_fpa_mode: u8,  // boolean_T (unsigned char)
    pub true_mode: u8,  // boolean_T (unsigned char)
    pub mach_mode: u8,  // boolean_T (unsigned char)
    pub spd_mach_value: f64,
    pub spd_mach_dashes: u8,  // boolean_T (unsigned char)
    pub hdg_trk_value: f64,
    pub hdg_trk_dashes: u8,  // boolean_T (unsigned char)
    pub alt_value: f64,
    pub vs_fpa_value: f64,
    pub vs_fpa_dashes: u8,  // boolean_T (unsigned char)
    pub afs_cp_active: u8,  // boolean_T (unsigned char)
}

/// `base_fcu_discrete_outputs` in A380FcuComputer_types.h.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct BaseFcuDiscreteOutputs {
    pub efis_outputs: BaseFcuEfisPanelOutputs,
    pub afs_outputs: BaseFcuAfsPanelOutputs,
    pub true_selected: u8,  // boolean_T (unsigned char)
    pub fcu_healthy: u8,  // boolean_T (unsigned char)
}

// Layout contract with src/fbw_cpp/fbw_types_layout.h (same numbers).
const _: () = {
    assert!(size_of::<BaseTime>() == 24 && align_of::<BaseTime>() == 8);
    assert!(offset_of!(BaseTime, dt) == 0);
    assert!(offset_of!(BaseTime, simulation_time) == 8);
    assert!(offset_of!(BaseTime, monotonic_time) == 16);
    assert!(size_of::<BaseSimData>() == 5 && align_of::<BaseSimData>() == 1);
    assert!(offset_of!(BaseSimData, slew_on) == 0);
    assert!(offset_of!(BaseSimData, pause_on) == 1);
    assert!(offset_of!(BaseSimData, tracking_mode_on_override) == 2);
    assert!(offset_of!(BaseSimData, tailstrike_protection_on) == 3);
    assert!(offset_of!(BaseSimData, computer_running) == 4);
    assert!(size_of::<BasePrimSimInput>() == 16 && align_of::<BasePrimSimInput>() == 4);
    assert!(offset_of!(BasePrimSimInput, spd_mach) == 0);
    assert!(offset_of!(BasePrimSimInput, hdg_trk) == 4);
    assert!(offset_of!(BasePrimSimInput, alt) == 8);
    assert!(offset_of!(BasePrimSimInput, vs_fpa) == 12);
    assert!(size_of::<BasePrimDiscreteInputs>() == 32 && align_of::<BasePrimDiscreteInputs>() == 8);
    assert!(offset_of!(BasePrimDiscreteInputs, alignment_dummy) == 0);
    assert!(offset_of!(BasePrimDiscreteInputs, prim_overhead_button_pressed) == 8);
    assert!(offset_of!(BasePrimDiscreteInputs, is_unit_1) == 9);
    assert!(offset_of!(BasePrimDiscreteInputs, is_unit_2) == 10);
    assert!(offset_of!(BasePrimDiscreteInputs, is_unit_3) == 11);
    assert!(offset_of!(BasePrimDiscreteInputs, capt_priority_takeover_pressed) == 12);
    assert!(offset_of!(BasePrimDiscreteInputs, fo_priority_takeover_pressed) == 13);
    assert!(offset_of!(BasePrimDiscreteInputs, ap_1_pushbutton_pressed) == 14);
    assert!(offset_of!(BasePrimDiscreteInputs, ap_2_pushbutton_pressed) == 15);
    assert!(offset_of!(BasePrimDiscreteInputs, fcu_1_healthy) == 16);
    assert!(offset_of!(BasePrimDiscreteInputs, fcu_2_healthy) == 17);
    assert!(offset_of!(BasePrimDiscreteInputs, athr_pushbutton) == 18);
    assert!(offset_of!(BasePrimDiscreteInputs, ir_3_on_capt) == 19);
    assert!(offset_of!(BasePrimDiscreteInputs, ir_3_on_fo) == 20);
    assert!(offset_of!(BasePrimDiscreteInputs, adr_3_on_capt) == 21);
    assert!(offset_of!(BasePrimDiscreteInputs, adr_3_on_fo) == 22);
    assert!(offset_of!(BasePrimDiscreteInputs, rat_deployed) == 23);
    assert!(offset_of!(BasePrimDiscreteInputs, rat_contactor_closed) == 24);
    assert!(offset_of!(BasePrimDiscreteInputs, athr_instinctive_disc) == 25);
    assert!(offset_of!(BasePrimDiscreteInputs, pitch_trim_up_pressed) == 26);
    assert!(offset_of!(BasePrimDiscreteInputs, pitch_trim_down_pressed) == 27);
    assert!(offset_of!(BasePrimDiscreteInputs, green_low_pressure) == 28);
    assert!(offset_of!(BasePrimDiscreteInputs, yellow_low_pressure) == 29);
    assert!(size_of::<BasePrimAnalogInputs>() == 272 && align_of::<BasePrimAnalogInputs>() == 8);
    assert!(offset_of!(BasePrimAnalogInputs, capt_pitch_stick_pos) == 0);
    assert!(offset_of!(BasePrimAnalogInputs, fo_pitch_stick_pos) == 8);
    assert!(offset_of!(BasePrimAnalogInputs, capt_roll_stick_pos) == 16);
    assert!(offset_of!(BasePrimAnalogInputs, fo_roll_stick_pos) == 24);
    assert!(offset_of!(BasePrimAnalogInputs, speed_brake_lever_pos) == 32);
    assert!(offset_of!(BasePrimAnalogInputs, thr_lever_1_pos) == 40);
    assert!(offset_of!(BasePrimAnalogInputs, thr_lever_2_pos) == 48);
    assert!(offset_of!(BasePrimAnalogInputs, thr_lever_3_pos) == 56);
    assert!(offset_of!(BasePrimAnalogInputs, thr_lever_4_pos) == 64);
    assert!(offset_of!(BasePrimAnalogInputs, elevator_1_pos_deg) == 72);
    assert!(offset_of!(BasePrimAnalogInputs, elevator_2_pos_deg) == 80);
    assert!(offset_of!(BasePrimAnalogInputs, elevator_3_pos_deg) == 88);
    assert!(offset_of!(BasePrimAnalogInputs, ths_pos_deg) == 96);
    assert!(offset_of!(BasePrimAnalogInputs, left_aileron_1_pos_deg) == 104);
    assert!(offset_of!(BasePrimAnalogInputs, left_aileron_2_pos_deg) == 112);
    assert!(offset_of!(BasePrimAnalogInputs, right_aileron_1_pos_deg) == 120);
    assert!(offset_of!(BasePrimAnalogInputs, right_aileron_2_pos_deg) == 128);
    assert!(offset_of!(BasePrimAnalogInputs, left_spoiler_pos_deg) == 136);
    assert!(offset_of!(BasePrimAnalogInputs, right_spoiler_pos_deg) == 144);
    assert!(offset_of!(BasePrimAnalogInputs, rudder_1_pos_deg) == 152);
    assert!(offset_of!(BasePrimAnalogInputs, rudder_2_pos_deg) == 160);
    assert!(offset_of!(BasePrimAnalogInputs, rudder_pedal_pos) == 168);
    assert!(offset_of!(BasePrimAnalogInputs, yellow_hyd_pressure_psi) == 176);
    assert!(offset_of!(BasePrimAnalogInputs, green_hyd_pressure_psi) == 184);
    assert!(offset_of!(BasePrimAnalogInputs, vert_acc_1_g) == 192);
    assert!(offset_of!(BasePrimAnalogInputs, vert_acc_2_g) == 200);
    assert!(offset_of!(BasePrimAnalogInputs, vert_acc_3_g) == 208);
    assert!(offset_of!(BasePrimAnalogInputs, lat_acc_1_g) == 216);
    assert!(offset_of!(BasePrimAnalogInputs, lat_acc_2_g) == 224);
    assert!(offset_of!(BasePrimAnalogInputs, lat_acc_3_g) == 232);
    assert!(offset_of!(BasePrimAnalogInputs, left_body_wheel_speed) == 240);
    assert!(offset_of!(BasePrimAnalogInputs, left_wing_wheel_speed) == 248);
    assert!(offset_of!(BasePrimAnalogInputs, right_body_wheel_speed) == 256);
    assert!(offset_of!(BasePrimAnalogInputs, right_wing_wheel_speed) == 264);
    assert!(size_of::<BaseArinc429>() == 8 && align_of::<BaseArinc429>() == 4);
    assert!(offset_of!(BaseArinc429, SSM) == 0);
    assert!(offset_of!(BaseArinc429, Data) == 4);
    assert!(size_of::<BaseAdrBus>() == 72 && align_of::<BaseAdrBus>() == 4);
    assert!(offset_of!(BaseAdrBus, altitude_standard_ft) == 0);
    assert!(offset_of!(BaseAdrBus, altitude_corrected_1_ft) == 8);
    assert!(offset_of!(BaseAdrBus, altitude_corrected_2_ft) == 16);
    assert!(offset_of!(BaseAdrBus, mach) == 24);
    assert!(offset_of!(BaseAdrBus, airspeed_computed_kn) == 32);
    assert!(offset_of!(BaseAdrBus, airspeed_true_kn) == 40);
    assert!(offset_of!(BaseAdrBus, vertical_speed_ft_min) == 48);
    assert!(offset_of!(BaseAdrBus, aoa_corrected_deg) == 56);
    assert!(offset_of!(BaseAdrBus, corrected_average_static_pressure) == 64);
    assert!(size_of::<BaseIrBus>() == 248 && align_of::<BaseIrBus>() == 4);
    assert!(offset_of!(BaseIrBus, discrete_word_1) == 0);
    assert!(offset_of!(BaseIrBus, latitude_deg) == 8);
    assert!(offset_of!(BaseIrBus, longitude_deg) == 16);
    assert!(offset_of!(BaseIrBus, ground_speed_kn) == 24);
    assert!(offset_of!(BaseIrBus, track_angle_true_deg) == 32);
    assert!(offset_of!(BaseIrBus, heading_true_deg) == 40);
    assert!(offset_of!(BaseIrBus, wind_speed_kn) == 48);
    assert!(offset_of!(BaseIrBus, wind_direction_true_deg) == 56);
    assert!(offset_of!(BaseIrBus, track_angle_magnetic_deg) == 64);
    assert!(offset_of!(BaseIrBus, heading_magnetic_deg) == 72);
    assert!(offset_of!(BaseIrBus, drift_angle_deg) == 80);
    assert!(offset_of!(BaseIrBus, flight_path_angle_deg) == 88);
    assert!(offset_of!(BaseIrBus, flight_path_accel_g) == 96);
    assert!(offset_of!(BaseIrBus, pitch_angle_deg) == 104);
    assert!(offset_of!(BaseIrBus, roll_angle_deg) == 112);
    assert!(offset_of!(BaseIrBus, body_pitch_rate_deg_s) == 120);
    assert!(offset_of!(BaseIrBus, body_roll_rate_deg_s) == 128);
    assert!(offset_of!(BaseIrBus, body_yaw_rate_deg_s) == 136);
    assert!(offset_of!(BaseIrBus, body_long_accel_g) == 144);
    assert!(offset_of!(BaseIrBus, body_lat_accel_g) == 152);
    assert!(offset_of!(BaseIrBus, body_normal_accel_g) == 160);
    assert!(offset_of!(BaseIrBus, track_angle_rate_deg_s) == 168);
    assert!(offset_of!(BaseIrBus, pitch_att_rate_deg_s) == 176);
    assert!(offset_of!(BaseIrBus, roll_att_rate_deg_s) == 184);
    assert!(offset_of!(BaseIrBus, inertial_alt_ft) == 192);
    assert!(offset_of!(BaseIrBus, along_track_horiz_acc_g) == 200);
    assert!(offset_of!(BaseIrBus, cross_track_horiz_acc_g) == 208);
    assert!(offset_of!(BaseIrBus, vertical_accel_g) == 216);
    assert!(offset_of!(BaseIrBus, inertial_vertical_speed_ft_s) == 224);
    assert!(offset_of!(BaseIrBus, north_south_velocity_kn) == 232);
    assert!(offset_of!(BaseIrBus, east_west_velocity_kn) == 240);
    assert!(size_of::<BaseRaBus>() == 8 && align_of::<BaseRaBus>() == 4);
    assert!(offset_of!(BaseRaBus, radio_height_ft) == 0);
    assert!(size_of::<BaseIlsBus>() == 32 && align_of::<BaseIlsBus>() == 4);
    assert!(offset_of!(BaseIlsBus, runway_heading_deg) == 0);
    assert!(offset_of!(BaseIlsBus, ils_frequency_mhz) == 8);
    assert!(offset_of!(BaseIlsBus, localizer_deviation_deg) == 16);
    assert!(offset_of!(BaseIlsBus, glideslope_deviation_deg) == 24);
    assert!(size_of::<BaseSfccBus>() == 40 && align_of::<BaseSfccBus>() == 4);
    assert!(offset_of!(BaseSfccBus, slat_flap_component_status_word) == 0);
    assert!(offset_of!(BaseSfccBus, slat_flap_system_status_word) == 8);
    assert!(offset_of!(BaseSfccBus, slat_flap_actual_position_word) == 16);
    assert!(offset_of!(BaseSfccBus, slat_actual_position_deg) == 24);
    assert!(offset_of!(BaseSfccBus, flap_actual_position_deg) == 32);
    assert!(size_of::<BaseLgciuBus>() == 32 && align_of::<BaseLgciuBus>() == 4);
    assert!(offset_of!(BaseLgciuBus, discrete_word_1) == 0);
    assert!(offset_of!(BaseLgciuBus, discrete_word_2) == 8);
    assert!(offset_of!(BaseLgciuBus, discrete_word_3) == 16);
    assert!(offset_of!(BaseLgciuBus, discrete_word_4) == 24);
    assert!(size_of::<BaseFcuBus>() == 48 && align_of::<BaseFcuBus>() == 4);
    assert!(offset_of!(BaseFcuBus, efis_discrete_word_1) == 0);
    assert!(offset_of!(BaseFcuBus, efis_discrete_word_2) == 8);
    assert!(offset_of!(BaseFcuBus, baro_setting_hpa) == 16);
    assert!(offset_of!(BaseFcuBus, baro_setting_inhg) == 24);
    assert!(offset_of!(BaseFcuBus, afs_discrete_word_1) == 32);
    assert!(offset_of!(BaseFcuBus, afs_discrete_word_2) == 40);
    assert!(size_of::<BasePrimFctlOutBus>() == 456 && align_of::<BasePrimFctlOutBus>() == 4);
    assert!(offset_of!(BasePrimFctlOutBus, left_inboard_aileron_command_deg) == 0);
    assert!(offset_of!(BasePrimFctlOutBus, right_inboard_aileron_command_deg) == 8);
    assert!(offset_of!(BasePrimFctlOutBus, left_midboard_aileron_command_deg) == 16);
    assert!(offset_of!(BasePrimFctlOutBus, right_midboard_aileron_command_deg) == 24);
    assert!(offset_of!(BasePrimFctlOutBus, left_outboard_aileron_command_deg) == 32);
    assert!(offset_of!(BasePrimFctlOutBus, right_outboard_aileron_command_deg) == 40);
    assert!(offset_of!(BasePrimFctlOutBus, left_spoiler_1_command_deg) == 48);
    assert!(offset_of!(BasePrimFctlOutBus, right_spoiler_1_command_deg) == 56);
    assert!(offset_of!(BasePrimFctlOutBus, left_spoiler_2_command_deg) == 64);
    assert!(offset_of!(BasePrimFctlOutBus, right_spoiler_2_command_deg) == 72);
    assert!(offset_of!(BasePrimFctlOutBus, left_spoiler_3_command_deg) == 80);
    assert!(offset_of!(BasePrimFctlOutBus, right_spoiler_3_command_deg) == 88);
    assert!(offset_of!(BasePrimFctlOutBus, left_spoiler_4_command_deg) == 96);
    assert!(offset_of!(BasePrimFctlOutBus, right_spoiler_4_command_deg) == 104);
    assert!(offset_of!(BasePrimFctlOutBus, left_spoiler_5_command_deg) == 112);
    assert!(offset_of!(BasePrimFctlOutBus, right_spoiler_5_command_deg) == 120);
    assert!(offset_of!(BasePrimFctlOutBus, left_spoiler_6_command_deg) == 128);
    assert!(offset_of!(BasePrimFctlOutBus, right_spoiler_6_command_deg) == 136);
    assert!(offset_of!(BasePrimFctlOutBus, left_spoiler_7_command_deg) == 144);
    assert!(offset_of!(BasePrimFctlOutBus, right_spoiler_7_command_deg) == 152);
    assert!(offset_of!(BasePrimFctlOutBus, left_spoiler_8_command_deg) == 160);
    assert!(offset_of!(BasePrimFctlOutBus, right_spoiler_8_command_deg) == 168);
    assert!(offset_of!(BasePrimFctlOutBus, left_inboard_elevator_command_deg) == 176);
    assert!(offset_of!(BasePrimFctlOutBus, right_inboard_elevator_command_deg) == 184);
    assert!(offset_of!(BasePrimFctlOutBus, left_outboard_elevator_command_deg) == 192);
    assert!(offset_of!(BasePrimFctlOutBus, right_outboard_elevator_command_deg) == 200);
    assert!(offset_of!(BasePrimFctlOutBus, ths_command_deg) == 208);
    assert!(offset_of!(BasePrimFctlOutBus, upper_rudder_command_deg) == 216);
    assert!(offset_of!(BasePrimFctlOutBus, lower_rudder_command_deg) == 224);
    assert!(offset_of!(BasePrimFctlOutBus, left_sidestick_pitch_command_deg) == 232);
    assert!(offset_of!(BasePrimFctlOutBus, right_sidestick_pitch_command_deg) == 240);
    assert!(offset_of!(BasePrimFctlOutBus, left_sidestick_roll_command_deg) == 248);
    assert!(offset_of!(BasePrimFctlOutBus, right_sidestick_roll_command_deg) == 256);
    assert!(offset_of!(BasePrimFctlOutBus, rudder_pedal_position_deg) == 264);
    assert!(offset_of!(BasePrimFctlOutBus, aileron_status_word) == 272);
    assert!(offset_of!(BasePrimFctlOutBus, left_aileron_1_position_deg) == 280);
    assert!(offset_of!(BasePrimFctlOutBus, left_aileron_2_position_deg) == 288);
    assert!(offset_of!(BasePrimFctlOutBus, right_aileron_1_position_deg) == 296);
    assert!(offset_of!(BasePrimFctlOutBus, right_aileron_2_position_deg) == 304);
    assert!(offset_of!(BasePrimFctlOutBus, spoiler_status_word) == 312);
    assert!(offset_of!(BasePrimFctlOutBus, left_spoiler_position_deg) == 320);
    assert!(offset_of!(BasePrimFctlOutBus, right_spoiler_position_deg) == 328);
    assert!(offset_of!(BasePrimFctlOutBus, elevator_status_word) == 336);
    assert!(offset_of!(BasePrimFctlOutBus, elevator_1_position_deg) == 344);
    assert!(offset_of!(BasePrimFctlOutBus, elevator_2_position_deg) == 352);
    assert!(offset_of!(BasePrimFctlOutBus, elevator_3_position_deg) == 360);
    assert!(offset_of!(BasePrimFctlOutBus, ths_position_deg) == 368);
    assert!(offset_of!(BasePrimFctlOutBus, rudder_status_word) == 376);
    assert!(offset_of!(BasePrimFctlOutBus, rudder_1_position_deg) == 384);
    assert!(offset_of!(BasePrimFctlOutBus, rudder_2_position_deg) == 392);
    assert!(offset_of!(BasePrimFctlOutBus, radio_height_1_ft) == 400);
    assert!(offset_of!(BasePrimFctlOutBus, radio_height_2_ft) == 408);
    assert!(offset_of!(BasePrimFctlOutBus, fctl_law_status_word) == 416);
    assert!(offset_of!(BasePrimFctlOutBus, discrete_status_word_1) == 424);
    assert!(offset_of!(BasePrimFctlOutBus, v_alpha_lim_kn) == 432);
    assert!(offset_of!(BasePrimFctlOutBus, v_alpha_prot_kn) == 440);
    assert!(offset_of!(BasePrimFctlOutBus, v_alpha_stall_warn_kn) == 448);
    assert!(size_of::<BasePrimFeOutBus>() == 96 && align_of::<BasePrimFeOutBus>() == 4);
    assert!(offset_of!(BasePrimFeOutBus, gamma_a_deg) == 0);
    assert!(offset_of!(BasePrimFeOutBus, gamma_t_deg) == 8);
    assert!(offset_of!(BasePrimFeOutBus, sideslip_target_deg) == 16);
    assert!(offset_of!(BasePrimFeOutBus, v_ls_kn) == 24);
    assert!(offset_of!(BasePrimFeOutBus, v_stall_kn) == 32);
    assert!(offset_of!(BasePrimFeOutBus, speed_trend_kn) == 40);
    assert!(offset_of!(BasePrimFeOutBus, v_3_kn) == 48);
    assert!(offset_of!(BasePrimFeOutBus, v_4_kn) == 56);
    assert!(offset_of!(BasePrimFeOutBus, v_man_kn) == 64);
    assert!(offset_of!(BasePrimFeOutBus, v_max_kn) == 72);
    assert!(offset_of!(BasePrimFeOutBus, v_fe_next_kn) == 80);
    assert!(offset_of!(BasePrimFeOutBus, discrete_word_1) == 88);
    assert!(size_of::<BasePrimFgOutBus>() == 264 && align_of::<BasePrimFgOutBus>() == 4);
    assert!(offset_of!(BasePrimFgOutBus, pfd_spd_tgt_kts) == 0);
    assert!(offset_of!(BasePrimFgOutBus, pfd_short_term_mngd_spd_kts) == 8);
    assert!(offset_of!(BasePrimFgOutBus, selected_spd_kts) == 16);
    assert!(offset_of!(BasePrimFgOutBus, selected_mach_kts) == 24);
    assert!(offset_of!(BasePrimFgOutBus, selected_hdg_deg) == 32);
    assert!(offset_of!(BasePrimFgOutBus, selected_trk_deg) == 40);
    assert!(offset_of!(BasePrimFgOutBus, selected_alt_ft) == 48);
    assert!(offset_of!(BasePrimFgOutBus, selected_vs_ft_min) == 56);
    assert!(offset_of!(BasePrimFgOutBus, selected_fpa_deg) == 64);
    assert!(offset_of!(BasePrimFgOutBus, runway_hdg_memorized_deg) == 72);
    assert!(offset_of!(BasePrimFgOutBus, preset_mach_from_fms) == 80);
    assert!(offset_of!(BasePrimFgOutBus, preset_speed_from_fms_kts) == 88);
    assert!(offset_of!(BasePrimFgOutBus, roll_fd_command_1) == 96);
    assert!(offset_of!(BasePrimFgOutBus, pitch_fd_command_1) == 104);
    assert!(offset_of!(BasePrimFgOutBus, yaw_fd_command_1) == 112);
    assert!(offset_of!(BasePrimFgOutBus, roll_fd_command_2) == 120);
    assert!(offset_of!(BasePrimFgOutBus, pitch_fd_command_2) == 128);
    assert!(offset_of!(BasePrimFgOutBus, yaw_fd_command_2) == 136);
    assert!(offset_of!(BasePrimFgOutBus, discrete_word_1) == 144);
    assert!(offset_of!(BasePrimFgOutBus, fm_alt_constraint_ft) == 152);
    assert!(offset_of!(BasePrimFgOutBus, ats_discrete_word) == 160);
    assert!(offset_of!(BasePrimFgOutBus, ats_fma_discrete_word) == 168);
    assert!(offset_of!(BasePrimFgOutBus, discrete_word_2) == 176);
    assert!(offset_of!(BasePrimFgOutBus, discrete_word_3) == 184);
    assert!(offset_of!(BasePrimFgOutBus, discrete_word_4) == 192);
    assert!(offset_of!(BasePrimFgOutBus, discrete_word_5) == 200);
    assert!(offset_of!(BasePrimFgOutBus, discrete_word_6) == 208);
    assert!(offset_of!(BasePrimFgOutBus, low_target_speed_margin_kts) == 216);
    assert!(offset_of!(BasePrimFgOutBus, high_target_speed_margin_kts) == 224);
    assert!(offset_of!(BasePrimFgOutBus, nosewheel_cmd_deg) == 232);
    assert!(offset_of!(BasePrimFgOutBus, n1_command_percent) == 240);
    assert!(offset_of!(BasePrimFgOutBus, flx_to_temp_deg_c) == 248);
    assert!(offset_of!(BasePrimFgOutBus, discrete_word_7) == 256);
    assert!(size_of::<BasePrimOutBus>() == 816 && align_of::<BasePrimOutBus>() == 4);
    assert!(offset_of!(BasePrimOutBus, fctl) == 0);
    assert!(offset_of!(BasePrimOutBus, fe) == 456);
    assert!(offset_of!(BasePrimOutBus, fg) == 552);
    assert!(size_of::<BaseSecOutBus>() == 208 && align_of::<BaseSecOutBus>() == 4);
    assert!(offset_of!(BaseSecOutBus, left_sidestick_pitch_command_deg) == 0);
    assert!(offset_of!(BaseSecOutBus, right_sidestick_pitch_command_deg) == 8);
    assert!(offset_of!(BaseSecOutBus, left_sidestick_roll_command_deg) == 16);
    assert!(offset_of!(BaseSecOutBus, right_sidestick_roll_command_deg) == 24);
    assert!(offset_of!(BaseSecOutBus, rudder_pedal_position_deg) == 32);
    assert!(offset_of!(BaseSecOutBus, aileron_status_word) == 40);
    assert!(offset_of!(BaseSecOutBus, left_aileron_1_position_deg) == 48);
    assert!(offset_of!(BaseSecOutBus, left_aileron_2_position_deg) == 56);
    assert!(offset_of!(BaseSecOutBus, right_aileron_1_position_deg) == 64);
    assert!(offset_of!(BaseSecOutBus, right_aileron_2_position_deg) == 72);
    assert!(offset_of!(BaseSecOutBus, spoiler_status_word) == 80);
    assert!(offset_of!(BaseSecOutBus, left_spoiler_1_position_deg) == 88);
    assert!(offset_of!(BaseSecOutBus, right_spoiler_1_position_deg) == 96);
    assert!(offset_of!(BaseSecOutBus, left_spoiler_2_position_deg) == 104);
    assert!(offset_of!(BaseSecOutBus, right_spoiler_2_position_deg) == 112);
    assert!(offset_of!(BaseSecOutBus, elevator_status_word) == 120);
    assert!(offset_of!(BaseSecOutBus, elevator_1_position_deg) == 128);
    assert!(offset_of!(BaseSecOutBus, elevator_2_position_deg) == 136);
    assert!(offset_of!(BaseSecOutBus, elevator_3_position_deg) == 144);
    assert!(offset_of!(BaseSecOutBus, ths_position_deg) == 152);
    assert!(offset_of!(BaseSecOutBus, rudder_status_word) == 160);
    assert!(offset_of!(BaseSecOutBus, rudder_1_position_deg) == 168);
    assert!(offset_of!(BaseSecOutBus, rudder_2_position_deg) == 176);
    assert!(offset_of!(BaseSecOutBus, rudder_trim_actual_pos_deg) == 184);
    assert!(offset_of!(BaseSecOutBus, fctl_law_status_word) == 192);
    assert!(offset_of!(BaseSecOutBus, misc_data_status_word) == 200);
    assert!(size_of::<BasePrimBusInputs>() == 3640 && align_of::<BasePrimBusInputs>() == 8);
    assert!(offset_of!(BasePrimBusInputs, adr_1_bus) == 0);
    assert!(offset_of!(BasePrimBusInputs, adr_2_bus) == 72);
    assert!(offset_of!(BasePrimBusInputs, adr_3_bus) == 144);
    assert!(offset_of!(BasePrimBusInputs, ir_1_bus) == 216);
    assert!(offset_of!(BasePrimBusInputs, ir_2_bus) == 464);
    assert!(offset_of!(BasePrimBusInputs, ir_3_bus) == 712);
    assert!(offset_of!(BasePrimBusInputs, isis_1_bus) == 960);
    assert!(offset_of!(BasePrimBusInputs, isis_2_bus) == 968);
    assert!(offset_of!(BasePrimBusInputs, rate_gyro_pitch_1_bus) == 976);
    assert!(offset_of!(BasePrimBusInputs, rate_gyro_pitch_2_bus) == 984);
    assert!(offset_of!(BasePrimBusInputs, rate_gyro_roll_1_bus) == 992);
    assert!(offset_of!(BasePrimBusInputs, rate_gyro_roll_2_bus) == 1000);
    assert!(offset_of!(BasePrimBusInputs, rate_gyro_yaw_1_bus) == 1008);
    assert!(offset_of!(BasePrimBusInputs, rate_gyro_yaw_2_bus) == 1016);
    assert!(offset_of!(BasePrimBusInputs, ra_1_bus) == 1024);
    assert!(offset_of!(BasePrimBusInputs, ra_2_bus) == 1032);
    assert!(offset_of!(BasePrimBusInputs, ils_1_bus) == 1040);
    assert!(offset_of!(BasePrimBusInputs, ils_2_bus) == 1072);
    assert!(offset_of!(BasePrimBusInputs, sfcc_1_bus) == 1104);
    assert!(offset_of!(BasePrimBusInputs, sfcc_2_bus) == 1144);
    assert!(offset_of!(BasePrimBusInputs, lgciu_1_bus) == 1184);
    assert!(offset_of!(BasePrimBusInputs, lgciu_2_bus) == 1216);
    assert!(offset_of!(BasePrimBusInputs, irdc_1_bus) == 1248);
    assert!(offset_of!(BasePrimBusInputs, irdc_2_bus) == 1256);
    assert!(offset_of!(BasePrimBusInputs, irdc_3_bus) == 1264);
    assert!(offset_of!(BasePrimBusInputs, irdc_4_a_bus) == 1272);
    assert!(offset_of!(BasePrimBusInputs, irdc_4_b_bus) == 1280);
    assert!(offset_of!(BasePrimBusInputs, fcu_1_bus) == 1288);
    assert!(offset_of!(BasePrimBusInputs, fcu_2_bus) == 1336);
    assert!(offset_of!(BasePrimBusInputs, prim_x_bus) == 1384);
    assert!(offset_of!(BasePrimBusInputs, prim_y_bus) == 2200);
    assert!(offset_of!(BasePrimBusInputs, sec_1_bus) == 3016);
    assert!(offset_of!(BasePrimBusInputs, sec_2_bus) == 3224);
    assert!(offset_of!(BasePrimBusInputs, sec_3_bus) == 3432);
    assert!(size_of::<BaseFmsInputs>() == 232 && align_of::<BaseFmsInputs>() == 8);
    assert!(offset_of!(BaseFmsInputs, fm_valid) == 0);
    assert!(offset_of!(BaseFmsInputs, active_fms_flight_phase) == 4);
    assert!(offset_of!(BaseFmsInputs, selected_approach_type) == 8);
    assert!(offset_of!(BaseFmsInputs, backbeam_selected) == 12);
    assert!(offset_of!(BaseFmsInputs, fms_loc_distance) == 16);
    assert!(offset_of!(BaseFmsInputs, fms_unrealistic_gs_angle_deg) == 24);
    assert!(offset_of!(BaseFmsInputs, lateral_flight_plan_valid) == 32);
    assert!(offset_of!(BaseFmsInputs, nav_capture_condition) == 33);
    assert!(offset_of!(BaseFmsInputs, phi_c_deg) == 40);
    assert!(offset_of!(BaseFmsInputs, xtk_nmi) == 48);
    assert!(offset_of!(BaseFmsInputs, tke_deg) == 56);
    assert!(offset_of!(BaseFmsInputs, phi_limit_deg) == 64);
    assert!(offset_of!(BaseFmsInputs, direct_to_nav_engage) == 72);
    assert!(offset_of!(BaseFmsInputs, vertical_flight_plan_valid) == 73);
    assert!(offset_of!(BaseFmsInputs, final_app_can_engage) == 74);
    assert!(offset_of!(BaseFmsInputs, next_alt_cstr_ft) == 80);
    assert!(offset_of!(BaseFmsInputs, requested_des_submode) == 88);
    assert!(offset_of!(BaseFmsInputs, alt_profile_tgt_ft) == 96);
    assert!(offset_of!(BaseFmsInputs, vs_target_ft_min) == 104);
    assert!(offset_of!(BaseFmsInputs, v_2_kts) == 112);
    assert!(offset_of!(BaseFmsInputs, v_app_kts) == 120);
    assert!(offset_of!(BaseFmsInputs, v_managed_kts) == 128);
    assert!(offset_of!(BaseFmsInputs, v_upper_margin_kts) == 136);
    assert!(offset_of!(BaseFmsInputs, v_lower_margin_kts) == 144);
    assert!(offset_of!(BaseFmsInputs, show_speed_margins) == 152);
    assert!(offset_of!(BaseFmsInputs, preset_spd_kts) == 160);
    assert!(offset_of!(BaseFmsInputs, preset_mach) == 168);
    assert!(offset_of!(BaseFmsInputs, preset_spd_mach_activate) == 176);
    assert!(offset_of!(BaseFmsInputs, fms_spd_mode_activate) == 177);
    assert!(offset_of!(BaseFmsInputs, fms_mach_mode_activate) == 178);
    assert!(offset_of!(BaseFmsInputs, flex_temp_deg_c) == 184);
    assert!(offset_of!(BaseFmsInputs, acceleration_alt_ft) == 192);
    assert!(offset_of!(BaseFmsInputs, thrust_reduction_alt_ft) == 200);
    assert!(offset_of!(BaseFmsInputs, cruise_alt_ft) == 208);
    assert!(offset_of!(BaseFmsInputs, tower_headwind_kn) == 216);
    assert!(offset_of!(BaseFmsInputs, flap_3_approach_selected) == 224);
    assert!(size_of::<BaseFqms>() == 16 && align_of::<BaseFqms>() == 4);
    assert!(offset_of!(BaseFqms, gross_weight_kg) == 0);
    assert!(offset_of!(BaseFqms, gross_weight_cg_pct) == 8);
    assert!(size_of::<BaseEec>() == 104 && align_of::<BaseEec>() == 4);
    assert!(offset_of!(BaseEec, selected_tla_deg) == 0);
    assert!(offset_of!(BaseEec, n1_ref_percent) == 8);
    assert!(offset_of!(BaseEec, selected_flex_temp_deg) == 16);
    assert!(offset_of!(BaseEec, ecu_status_word_1) == 24);
    assert!(offset_of!(BaseEec, ecu_status_word_2) == 32);
    assert!(offset_of!(BaseEec, ecu_status_word_3) == 40);
    assert!(offset_of!(BaseEec, ecu_status_word_4) == 48);
    assert!(offset_of!(BaseEec, n1_limit_percent) == 56);
    assert!(offset_of!(BaseEec, n1_maximum_percent) == 64);
    assert!(offset_of!(BaseEec, n1_command_percent) == 72);
    assert!(offset_of!(BaseEec, selected_n2_actual_percent) == 80);
    assert!(offset_of!(BaseEec, selected_n1_actual_percent) == 88);
    assert!(offset_of!(BaseEec, ecu_maintenance_word_6) == 96);
    assert!(size_of::<BaseTcas>() == 24 && align_of::<BaseTcas>() == 8);
    assert!(offset_of!(BaseTcas, tcas_valid) == 0);
    assert!(offset_of!(BaseTcas, ta_ra_mode) == 1);
    assert!(offset_of!(BaseTcas, ta_active) == 2);
    assert!(offset_of!(BaseTcas, ra_active) == 3);
    assert!(offset_of!(BaseTcas, ra_rate_to_maintain) == 8);
    assert!(offset_of!(BaseTcas, ra_corrective) == 16);
    assert!(size_of::<BasePrimAdcnInputs>() == 688 && align_of::<BasePrimAdcnInputs>() == 8);
    assert!(offset_of!(BasePrimAdcnInputs, fms) == 0);
    assert!(offset_of!(BasePrimAdcnInputs, fqms) == 232);
    assert!(offset_of!(BasePrimAdcnInputs, eec_1) == 248);
    assert!(offset_of!(BasePrimAdcnInputs, eec_2) == 352);
    assert!(offset_of!(BasePrimAdcnInputs, eec_3) == 456);
    assert!(offset_of!(BasePrimAdcnInputs, eec_4) == 560);
    assert!(offset_of!(BasePrimAdcnInputs, tcas) == 664);
    assert!(size_of::<PrimInputs>() == 4680 && align_of::<PrimInputs>() == 8);
    assert!(offset_of!(PrimInputs, time) == 0);
    assert!(offset_of!(PrimInputs, sim_data) == 24);
    assert!(offset_of!(PrimInputs, sim_input) == 32);
    assert!(offset_of!(PrimInputs, discrete_inputs) == 48);
    assert!(offset_of!(PrimInputs, analog_inputs) == 80);
    assert!(offset_of!(PrimInputs, bus_inputs) == 352);
    assert!(offset_of!(PrimInputs, adcn_inputs) == 3992);
    assert!(size_of::<BasePrimDiscreteOutputs>() == 32 && align_of::<BasePrimDiscreteOutputs>() == 8);
    assert!(offset_of!(BasePrimDiscreteOutputs, alignment_dummy) == 0);
    assert!(offset_of!(BasePrimDiscreteOutputs, elevator_1_active_mode) == 8);
    assert!(offset_of!(BasePrimDiscreteOutputs, elevator_2_active_mode) == 9);
    assert!(offset_of!(BasePrimDiscreteOutputs, elevator_3_active_mode) == 10);
    assert!(offset_of!(BasePrimDiscreteOutputs, ths_active_mode) == 11);
    assert!(offset_of!(BasePrimDiscreteOutputs, left_aileron_1_active_mode) == 12);
    assert!(offset_of!(BasePrimDiscreteOutputs, left_aileron_2_active_mode) == 13);
    assert!(offset_of!(BasePrimDiscreteOutputs, right_aileron_1_active_mode) == 14);
    assert!(offset_of!(BasePrimDiscreteOutputs, right_aileron_2_active_mode) == 15);
    assert!(offset_of!(BasePrimDiscreteOutputs, left_spoiler_electronic_module_enable) == 16);
    assert!(offset_of!(BasePrimDiscreteOutputs, right_spoiler_electronic_module_enable) == 17);
    assert!(offset_of!(BasePrimDiscreteOutputs, rudder_1_hydraulic_active_mode) == 18);
    assert!(offset_of!(BasePrimDiscreteOutputs, rudder_1_electric_active_mode) == 19);
    assert!(offset_of!(BasePrimDiscreteOutputs, rudder_2_hydraulic_active_mode) == 20);
    assert!(offset_of!(BasePrimDiscreteOutputs, rudder_2_electric_active_mode) == 21);
    assert!(offset_of!(BasePrimDiscreteOutputs, prim_healthy) == 22);
    assert!(offset_of!(BasePrimDiscreteOutputs, fcu_1_select) == 23);
    assert!(offset_of!(BasePrimDiscreteOutputs, fcu_2_select) == 24);
    assert!(offset_of!(BasePrimDiscreteOutputs, ap_engaged) == 25);
    assert!(offset_of!(BasePrimDiscreteOutputs, reverser_tertiary_lock) == 26);
    assert!(size_of::<BasePrimAnalogOutputs>() == 96 && align_of::<BasePrimAnalogOutputs>() == 8);
    assert!(offset_of!(BasePrimAnalogOutputs, elevator_1_pos_order_deg) == 0);
    assert!(offset_of!(BasePrimAnalogOutputs, elevator_2_pos_order_deg) == 8);
    assert!(offset_of!(BasePrimAnalogOutputs, elevator_3_pos_order_deg) == 16);
    assert!(offset_of!(BasePrimAnalogOutputs, ths_pos_order_deg) == 24);
    assert!(offset_of!(BasePrimAnalogOutputs, left_aileron_1_pos_order_deg) == 32);
    assert!(offset_of!(BasePrimAnalogOutputs, left_aileron_2_pos_order_deg) == 40);
    assert!(offset_of!(BasePrimAnalogOutputs, right_aileron_1_pos_order_deg) == 48);
    assert!(offset_of!(BasePrimAnalogOutputs, right_aileron_2_pos_order_deg) == 56);
    assert!(offset_of!(BasePrimAnalogOutputs, left_spoiler_pos_order_deg) == 64);
    assert!(offset_of!(BasePrimAnalogOutputs, right_spoiler_pos_order_deg) == 72);
    assert!(offset_of!(BasePrimAnalogOutputs, rudder_1_pos_order_deg) == 80);
    assert!(offset_of!(BasePrimAnalogOutputs, rudder_2_pos_order_deg) == 88);
    assert!(size_of::<ApRawLawsFlare>() == 56 && align_of::<ApRawLawsFlare>() == 8);
    assert!(offset_of!(ApRawLawsFlare, condition_Flare) == 0);
    assert!(offset_of!(ApRawLawsFlare, H_dot_radio_fpm) == 8);
    assert!(offset_of!(ApRawLawsFlare, H_dot_c_fpm) == 16);
    assert!(offset_of!(ApRawLawsFlare, delta_Theta_H_dot_deg) == 24);
    assert!(offset_of!(ApRawLawsFlare, delta_Theta_bz_deg) == 32);
    assert!(offset_of!(ApRawLawsFlare, delta_Theta_bx_deg) == 40);
    assert!(offset_of!(ApRawLawsFlare, delta_Theta_beta_c_deg) == 48);
    assert!(size_of::<BasePrimSurfaceStatus>() == 21 && align_of::<BasePrimSurfaceStatus>() == 1);
    assert!(offset_of!(BasePrimSurfaceStatus, left_inboard_aileron_engaged) == 0);
    assert!(offset_of!(BasePrimSurfaceStatus, right_inboard_aileron_engaged) == 1);
    assert!(offset_of!(BasePrimSurfaceStatus, left_midboard_aileron_engaged) == 2);
    assert!(offset_of!(BasePrimSurfaceStatus, right_midboard_aileron_engaged) == 3);
    assert!(offset_of!(BasePrimSurfaceStatus, left_outboard_aileron_engaged) == 4);
    assert!(offset_of!(BasePrimSurfaceStatus, right_outboard_aileron_engaged) == 5);
    assert!(offset_of!(BasePrimSurfaceStatus, spoiler_pair_1_engaged) == 6);
    assert!(offset_of!(BasePrimSurfaceStatus, spoiler_pair_2_engaged) == 7);
    assert!(offset_of!(BasePrimSurfaceStatus, spoiler_pair_3_engaged) == 8);
    assert!(offset_of!(BasePrimSurfaceStatus, spoiler_pair_4_engaged) == 9);
    assert!(offset_of!(BasePrimSurfaceStatus, spoiler_pair_5_engaged) == 10);
    assert!(offset_of!(BasePrimSurfaceStatus, spoiler_pair_6_engaged) == 11);
    assert!(offset_of!(BasePrimSurfaceStatus, spoiler_pair_7_engaged) == 12);
    assert!(offset_of!(BasePrimSurfaceStatus, spoiler_pair_8_engaged) == 13);
    assert!(offset_of!(BasePrimSurfaceStatus, left_inboard_elevator_engaged) == 14);
    assert!(offset_of!(BasePrimSurfaceStatus, right_inboard_elevator_engaged) == 15);
    assert!(offset_of!(BasePrimSurfaceStatus, left_outboard_elevator_engaged) == 16);
    assert!(offset_of!(BasePrimSurfaceStatus, right_outboard_elevator_engaged) == 17);
    assert!(offset_of!(BasePrimSurfaceStatus, ths_engaged) == 18);
    assert!(offset_of!(BasePrimSurfaceStatus, upper_rudder_engaged) == 19);
    assert!(offset_of!(BasePrimSurfaceStatus, lower_rudder_engaged) == 20);
    assert!(size_of::<BasePrimLateralSurfacePositions>() == 192 && align_of::<BasePrimLateralSurfacePositions>() == 8);
    assert!(offset_of!(BasePrimLateralSurfacePositions, left_inboard_aileron_deg) == 0);
    assert!(offset_of!(BasePrimLateralSurfacePositions, right_inboard_aileron_deg) == 8);
    assert!(offset_of!(BasePrimLateralSurfacePositions, left_midboard_aileron_deg) == 16);
    assert!(offset_of!(BasePrimLateralSurfacePositions, right_midboard_aileron_deg) == 24);
    assert!(offset_of!(BasePrimLateralSurfacePositions, left_outboard_aileron_deg) == 32);
    assert!(offset_of!(BasePrimLateralSurfacePositions, right_outboard_aileron_deg) == 40);
    assert!(offset_of!(BasePrimLateralSurfacePositions, left_spoiler_1_deg) == 48);
    assert!(offset_of!(BasePrimLateralSurfacePositions, right_spoiler_1_deg) == 56);
    assert!(offset_of!(BasePrimLateralSurfacePositions, left_spoiler_2_deg) == 64);
    assert!(offset_of!(BasePrimLateralSurfacePositions, right_spoiler_2_deg) == 72);
    assert!(offset_of!(BasePrimLateralSurfacePositions, left_spoiler_3_deg) == 80);
    assert!(offset_of!(BasePrimLateralSurfacePositions, right_spoiler_3_deg) == 88);
    assert!(offset_of!(BasePrimLateralSurfacePositions, left_spoiler_4_deg) == 96);
    assert!(offset_of!(BasePrimLateralSurfacePositions, right_spoiler_4_deg) == 104);
    assert!(offset_of!(BasePrimLateralSurfacePositions, left_spoiler_5_deg) == 112);
    assert!(offset_of!(BasePrimLateralSurfacePositions, right_spoiler_5_deg) == 120);
    assert!(offset_of!(BasePrimLateralSurfacePositions, left_spoiler_6_deg) == 128);
    assert!(offset_of!(BasePrimLateralSurfacePositions, right_spoiler_6_deg) == 136);
    assert!(offset_of!(BasePrimLateralSurfacePositions, left_spoiler_7_deg) == 144);
    assert!(offset_of!(BasePrimLateralSurfacePositions, right_spoiler_7_deg) == 152);
    assert!(offset_of!(BasePrimLateralSurfacePositions, left_spoiler_8_deg) == 160);
    assert!(offset_of!(BasePrimLateralSurfacePositions, right_spoiler_8_deg) == 168);
    assert!(offset_of!(BasePrimLateralSurfacePositions, upper_rudder_deg) == 176);
    assert!(offset_of!(BasePrimLateralSurfacePositions, lower_rudder_deg) == 184);
    assert!(size_of::<BasePrimPitchSurfacePositions>() == 40 && align_of::<BasePrimPitchSurfacePositions>() == 8);
    assert!(offset_of!(BasePrimPitchSurfacePositions, left_inboard_elevator_deg) == 0);
    assert!(offset_of!(BasePrimPitchSurfacePositions, right_inboard_elevator_deg) == 8);
    assert!(offset_of!(BasePrimPitchSurfacePositions, left_outboard_elevator_deg) == 16);
    assert!(offset_of!(BasePrimPitchSurfacePositions, right_outboard_elevator_deg) == 24);
    assert!(offset_of!(BasePrimPitchSurfacePositions, ths_deg) == 32);
    assert!(size_of::<BasePrimFctlLogicOutputs>() == 448 && align_of::<BasePrimFctlLogicOutputs>() == 8);
    assert!(offset_of!(BasePrimFctlLogicOutputs, surface_statuses) == 0);
    assert!(offset_of!(BasePrimFctlLogicOutputs, lateral_surface_positions) == 24);
    assert!(offset_of!(BasePrimFctlLogicOutputs, pitch_surface_positions) == 216);
    assert!(offset_of!(BasePrimFctlLogicOutputs, lateral_law_capability) == 256);
    assert!(offset_of!(BasePrimFctlLogicOutputs, active_lateral_law) == 260);
    assert!(offset_of!(BasePrimFctlLogicOutputs, pitch_law_capability) == 264);
    assert!(offset_of!(BasePrimFctlLogicOutputs, active_pitch_law) == 268);
    assert!(offset_of!(BasePrimFctlLogicOutputs, abnormal_condition_law_active) == 272);
    assert!(offset_of!(BasePrimFctlLogicOutputs, is_master_prim) == 273);
    assert!(offset_of!(BasePrimFctlLogicOutputs, elevator_1_avail) == 274);
    assert!(offset_of!(BasePrimFctlLogicOutputs, elevator_1_engaged) == 275);
    assert!(offset_of!(BasePrimFctlLogicOutputs, elevator_2_avail) == 276);
    assert!(offset_of!(BasePrimFctlLogicOutputs, elevator_2_engaged) == 277);
    assert!(offset_of!(BasePrimFctlLogicOutputs, elevator_3_avail) == 278);
    assert!(offset_of!(BasePrimFctlLogicOutputs, elevator_3_engaged) == 279);
    assert!(offset_of!(BasePrimFctlLogicOutputs, ths_avail) == 280);
    assert!(offset_of!(BasePrimFctlLogicOutputs, ths_engaged) == 281);
    assert!(offset_of!(BasePrimFctlLogicOutputs, left_aileron_1_avail) == 282);
    assert!(offset_of!(BasePrimFctlLogicOutputs, left_aileron_1_engaged) == 283);
    assert!(offset_of!(BasePrimFctlLogicOutputs, left_aileron_2_avail) == 284);
    assert!(offset_of!(BasePrimFctlLogicOutputs, left_aileron_2_engaged) == 285);
    assert!(offset_of!(BasePrimFctlLogicOutputs, right_aileron_1_avail) == 286);
    assert!(offset_of!(BasePrimFctlLogicOutputs, right_aileron_1_engaged) == 287);
    assert!(offset_of!(BasePrimFctlLogicOutputs, right_aileron_2_avail) == 288);
    assert!(offset_of!(BasePrimFctlLogicOutputs, right_aileron_2_engaged) == 289);
    assert!(offset_of!(BasePrimFctlLogicOutputs, left_spoiler_hydraulic_mode_avail) == 290);
    assert!(offset_of!(BasePrimFctlLogicOutputs, left_spoiler_electric_mode_avail) == 291);
    assert!(offset_of!(BasePrimFctlLogicOutputs, left_spoiler_hydraulic_mode_engaged) == 292);
    assert!(offset_of!(BasePrimFctlLogicOutputs, left_spoiler_electric_mode_engaged) == 293);
    assert!(offset_of!(BasePrimFctlLogicOutputs, right_spoiler_hydraulic_mode_avail) == 294);
    assert!(offset_of!(BasePrimFctlLogicOutputs, right_spoiler_electric_mode_avail) == 295);
    assert!(offset_of!(BasePrimFctlLogicOutputs, right_spoiler_hydraulic_mode_engaged) == 296);
    assert!(offset_of!(BasePrimFctlLogicOutputs, right_spoiler_electric_mode_engaged) == 297);
    assert!(offset_of!(BasePrimFctlLogicOutputs, rudder_1_hydraulic_mode_avail) == 298);
    assert!(offset_of!(BasePrimFctlLogicOutputs, rudder_1_electric_mode_avail) == 299);
    assert!(offset_of!(BasePrimFctlLogicOutputs, rudder_1_hydraulic_mode_engaged) == 300);
    assert!(offset_of!(BasePrimFctlLogicOutputs, rudder_1_electric_mode_engaged) == 301);
    assert!(offset_of!(BasePrimFctlLogicOutputs, rudder_2_hydraulic_mode_avail) == 302);
    assert!(offset_of!(BasePrimFctlLogicOutputs, rudder_2_electric_mode_avail) == 303);
    assert!(offset_of!(BasePrimFctlLogicOutputs, rudder_2_hydraulic_mode_engaged) == 304);
    assert!(offset_of!(BasePrimFctlLogicOutputs, rudder_2_electric_mode_engaged) == 305);
    assert!(offset_of!(BasePrimFctlLogicOutputs, aileron_droop_active) == 306);
    assert!(offset_of!(BasePrimFctlLogicOutputs, aileron_antidroop_active) == 307);
    assert!(offset_of!(BasePrimFctlLogicOutputs, ths_automatic_mode_active) == 308);
    assert!(offset_of!(BasePrimFctlLogicOutputs, ths_manual_mode_c_deg_s) == 312);
    assert!(offset_of!(BasePrimFctlLogicOutputs, eha_ebha_elec_mode_inhibited) == 320);
    assert!(offset_of!(BasePrimFctlLogicOutputs, left_sidestick_disabled) == 321);
    assert!(offset_of!(BasePrimFctlLogicOutputs, right_sidestick_disabled) == 322);
    assert!(offset_of!(BasePrimFctlLogicOutputs, left_sidestick_priority_locked) == 323);
    assert!(offset_of!(BasePrimFctlLogicOutputs, right_sidestick_priority_locked) == 324);
    assert!(offset_of!(BasePrimFctlLogicOutputs, total_sidestick_pitch_command) == 328);
    assert!(offset_of!(BasePrimFctlLogicOutputs, total_sidestick_roll_command) == 336);
    assert!(offset_of!(BasePrimFctlLogicOutputs, speed_brake_inhibited) == 344);
    assert!(offset_of!(BasePrimFctlLogicOutputs, speed_brake_command_deg) == 352);
    assert!(offset_of!(BasePrimFctlLogicOutputs, ground_spoilers_armed) == 360);
    assert!(offset_of!(BasePrimFctlLogicOutputs, ground_spoilers_out) == 361);
    assert!(offset_of!(BasePrimFctlLogicOutputs, phased_lift_dumping_active) == 362);
    assert!(offset_of!(BasePrimFctlLogicOutputs, ground_spoiler_command_deg) == 368);
    assert!(offset_of!(BasePrimFctlLogicOutputs, spoiler_lift_active) == 376);
    assert!(offset_of!(BasePrimFctlLogicOutputs, ap_authorised) == 377);
    assert!(offset_of!(BasePrimFctlLogicOutputs, protection_ap_disconnect) == 378);
    assert!(offset_of!(BasePrimFctlLogicOutputs, high_alpha_prot_active) == 379);
    assert!(offset_of!(BasePrimFctlLogicOutputs, alpha_prot_deg) == 384);
    assert!(offset_of!(BasePrimFctlLogicOutputs, alpha_max_deg) == 392);
    assert!(offset_of!(BasePrimFctlLogicOutputs, v_alpha_prot_kn) == 400);
    assert!(offset_of!(BasePrimFctlLogicOutputs, v_alpha_max_kn) == 408);
    assert!(offset_of!(BasePrimFctlLogicOutputs, v_alpha_stall_warn_kn) == 416);
    assert!(offset_of!(BasePrimFctlLogicOutputs, high_speed_prot_active) == 424);
    assert!(offset_of!(BasePrimFctlLogicOutputs, high_speed_prot_lo_thresh_kn) == 432);
    assert!(offset_of!(BasePrimFctlLogicOutputs, high_speed_prot_hi_thresh_kn) == 440);
    assert!(size_of::<BaseSecDiscreteInputs>() == 15 && align_of::<BaseSecDiscreteInputs>() == 1);
    assert!(offset_of!(BaseSecDiscreteInputs, sec_overhead_button_pressed) == 0);
    assert!(offset_of!(BaseSecDiscreteInputs, is_unit_1) == 1);
    assert!(offset_of!(BaseSecDiscreteInputs, is_unit_2) == 2);
    assert!(offset_of!(BaseSecDiscreteInputs, is_unit_3) == 3);
    assert!(offset_of!(BaseSecDiscreteInputs, capt_priority_takeover_pressed) == 4);
    assert!(offset_of!(BaseSecDiscreteInputs, fo_priority_takeover_pressed) == 5);
    assert!(offset_of!(BaseSecDiscreteInputs, rudder_trim_left_pressed) == 6);
    assert!(offset_of!(BaseSecDiscreteInputs, rudder_trim_right_pressed) == 7);
    assert!(offset_of!(BaseSecDiscreteInputs, rudder_trim_reset_pressed) == 8);
    assert!(offset_of!(BaseSecDiscreteInputs, pitch_trim_up_pressed) == 9);
    assert!(offset_of!(BaseSecDiscreteInputs, pitch_trim_down_pressed) == 10);
    assert!(offset_of!(BaseSecDiscreteInputs, rat_deployed) == 11);
    assert!(offset_of!(BaseSecDiscreteInputs, rat_contactor_closed) == 12);
    assert!(offset_of!(BaseSecDiscreteInputs, green_low_pressure) == 13);
    assert!(offset_of!(BaseSecDiscreteInputs, yellow_low_pressure) == 14);
    assert!(size_of::<BaseSecAnalogInputs>() == 160 && align_of::<BaseSecAnalogInputs>() == 8);
    assert!(offset_of!(BaseSecAnalogInputs, capt_pitch_stick_pos) == 0);
    assert!(offset_of!(BaseSecAnalogInputs, fo_pitch_stick_pos) == 8);
    assert!(offset_of!(BaseSecAnalogInputs, capt_roll_stick_pos) == 16);
    assert!(offset_of!(BaseSecAnalogInputs, fo_roll_stick_pos) == 24);
    assert!(offset_of!(BaseSecAnalogInputs, elevator_1_pos_deg) == 32);
    assert!(offset_of!(BaseSecAnalogInputs, elevator_2_pos_deg) == 40);
    assert!(offset_of!(BaseSecAnalogInputs, elevator_3_pos_deg) == 48);
    assert!(offset_of!(BaseSecAnalogInputs, ths_pos_deg) == 56);
    assert!(offset_of!(BaseSecAnalogInputs, left_aileron_1_pos_deg) == 64);
    assert!(offset_of!(BaseSecAnalogInputs, left_aileron_2_pos_deg) == 72);
    assert!(offset_of!(BaseSecAnalogInputs, right_aileron_1_pos_deg) == 80);
    assert!(offset_of!(BaseSecAnalogInputs, right_aileron_2_pos_deg) == 88);
    assert!(offset_of!(BaseSecAnalogInputs, left_spoiler_1_pos_deg) == 96);
    assert!(offset_of!(BaseSecAnalogInputs, right_spoiler_1_pos_deg) == 104);
    assert!(offset_of!(BaseSecAnalogInputs, left_spoiler_2_pos_deg) == 112);
    assert!(offset_of!(BaseSecAnalogInputs, right_spoiler_2_pos_deg) == 120);
    assert!(offset_of!(BaseSecAnalogInputs, rudder_1_pos_deg) == 128);
    assert!(offset_of!(BaseSecAnalogInputs, rudder_2_pos_deg) == 136);
    assert!(offset_of!(BaseSecAnalogInputs, rudder_pedal_pos_deg) == 144);
    assert!(offset_of!(BaseSecAnalogInputs, rudder_trim_actual_pos_deg) == 152);
    assert!(size_of::<BaseSecBusInputs>() == 3664 && align_of::<BaseSecBusInputs>() == 8);
    assert!(offset_of!(BaseSecBusInputs, adr_1_bus) == 0);
    assert!(offset_of!(BaseSecBusInputs, adr_2_bus) == 72);
    assert!(offset_of!(BaseSecBusInputs, ir_1_bus) == 144);
    assert!(offset_of!(BaseSecBusInputs, ir_2_bus) == 392);
    assert!(offset_of!(BaseSecBusInputs, sfcc_1_bus) == 640);
    assert!(offset_of!(BaseSecBusInputs, sfcc_2_bus) == 680);
    assert!(offset_of!(BaseSecBusInputs, lgciu_1_bus) == 720);
    assert!(offset_of!(BaseSecBusInputs, lgciu_2_bus) == 752);
    assert!(offset_of!(BaseSecBusInputs, irdc_5_a_bus) == 784);
    assert!(offset_of!(BaseSecBusInputs, irdc_5_b_bus) == 792);
    assert!(offset_of!(BaseSecBusInputs, prim_1_bus) == 800);
    assert!(offset_of!(BaseSecBusInputs, prim_2_bus) == 1616);
    assert!(offset_of!(BaseSecBusInputs, prim_3_bus) == 2432);
    assert!(offset_of!(BaseSecBusInputs, sec_x_bus) == 3248);
    assert!(offset_of!(BaseSecBusInputs, sec_y_bus) == 3456);
    assert!(size_of::<BaseSecAdcnInputs>() == 416 && align_of::<BaseSecAdcnInputs>() == 4);
    assert!(offset_of!(BaseSecAdcnInputs, eec_1) == 0);
    assert!(offset_of!(BaseSecAdcnInputs, eec_2) == 104);
    assert!(offset_of!(BaseSecAdcnInputs, eec_3) == 208);
    assert!(offset_of!(BaseSecAdcnInputs, eec_4) == 312);
    assert!(size_of::<SecInputs>() == 4288 && align_of::<SecInputs>() == 8);
    assert!(offset_of!(SecInputs, time) == 0);
    assert!(offset_of!(SecInputs, sim_data) == 24);
    assert!(offset_of!(SecInputs, discrete_inputs) == 29);
    assert!(offset_of!(SecInputs, analog_inputs) == 48);
    assert!(offset_of!(SecInputs, bus_inputs) == 208);
    assert!(offset_of!(SecInputs, adcn_inputs) == 3872);
    assert!(size_of::<BaseSecDiscreteOutputs>() == 14 && align_of::<BaseSecDiscreteOutputs>() == 1);
    assert!(offset_of!(BaseSecDiscreteOutputs, elevator_1_active_mode) == 0);
    assert!(offset_of!(BaseSecDiscreteOutputs, elevator_2_active_mode) == 1);
    assert!(offset_of!(BaseSecDiscreteOutputs, elevator_3_active_mode) == 2);
    assert!(offset_of!(BaseSecDiscreteOutputs, ths_active_mode) == 3);
    assert!(offset_of!(BaseSecDiscreteOutputs, left_aileron_1_active_mode) == 4);
    assert!(offset_of!(BaseSecDiscreteOutputs, left_aileron_2_active_mode) == 5);
    assert!(offset_of!(BaseSecDiscreteOutputs, right_aileron_1_active_mode) == 6);
    assert!(offset_of!(BaseSecDiscreteOutputs, right_aileron_2_active_mode) == 7);
    assert!(offset_of!(BaseSecDiscreteOutputs, rudder_1_hydraulic_active_mode) == 8);
    assert!(offset_of!(BaseSecDiscreteOutputs, rudder_1_electric_active_mode) == 9);
    assert!(offset_of!(BaseSecDiscreteOutputs, rudder_2_hydraulic_active_mode) == 10);
    assert!(offset_of!(BaseSecDiscreteOutputs, rudder_2_electric_active_mode) == 11);
    assert!(offset_of!(BaseSecDiscreteOutputs, rudder_trim_active_mode) == 12);
    assert!(offset_of!(BaseSecDiscreteOutputs, sec_healthy) == 13);
    assert!(size_of::<BaseSecAnalogOutputs>() == 120 && align_of::<BaseSecAnalogOutputs>() == 8);
    assert!(offset_of!(BaseSecAnalogOutputs, elevator_1_pos_order_deg) == 0);
    assert!(offset_of!(BaseSecAnalogOutputs, elevator_2_pos_order_deg) == 8);
    assert!(offset_of!(BaseSecAnalogOutputs, elevator_3_pos_order_deg) == 16);
    assert!(offset_of!(BaseSecAnalogOutputs, ths_pos_order_deg) == 24);
    assert!(offset_of!(BaseSecAnalogOutputs, left_aileron_1_pos_order_deg) == 32);
    assert!(offset_of!(BaseSecAnalogOutputs, left_aileron_2_pos_order_deg) == 40);
    assert!(offset_of!(BaseSecAnalogOutputs, right_aileron_1_pos_order_deg) == 48);
    assert!(offset_of!(BaseSecAnalogOutputs, right_aileron_2_pos_order_deg) == 56);
    assert!(offset_of!(BaseSecAnalogOutputs, left_spoiler_1_pos_order_deg) == 64);
    assert!(offset_of!(BaseSecAnalogOutputs, right_spoiler_1_pos_order_deg) == 72);
    assert!(offset_of!(BaseSecAnalogOutputs, left_spoiler_2_pos_order_deg) == 80);
    assert!(offset_of!(BaseSecAnalogOutputs, right_spoiler_2_pos_order_deg) == 88);
    assert!(offset_of!(BaseSecAnalogOutputs, rudder_1_pos_order_deg) == 96);
    assert!(offset_of!(BaseSecAnalogOutputs, rudder_2_pos_order_deg) == 104);
    assert!(offset_of!(BaseSecAnalogOutputs, rudder_trim_command_deg) == 112);
    assert!(size_of::<BaseFcuSimInput>() == 8 && align_of::<BaseFcuSimInput>() == 4);
    assert!(offset_of!(BaseFcuSimInput, baro_setting_hpa) == 0);
    assert!(offset_of!(BaseFcuSimInput, efis_mode) == 4);
    assert!(offset_of!(BaseFcuSimInput, efis_range) == 5);
    assert!(offset_of!(BaseFcuSimInput, navaid_1_mode) == 6);
    assert!(offset_of!(BaseFcuSimInput, navaid_2_mode) == 7);
    assert!(size_of::<BaseFcuKnobInputs>() == 3 && align_of::<BaseFcuKnobInputs>() == 1);
    assert!(offset_of!(BaseFcuKnobInputs, pushed) == 0);
    assert!(offset_of!(BaseFcuKnobInputs, pulled) == 1);
    assert!(offset_of!(BaseFcuKnobInputs, turns) == 2);
    assert!(size_of::<BaseFcuEfisPanelInputs>() == 19 && align_of::<BaseFcuEfisPanelInputs>() == 1);
    assert!(offset_of!(BaseFcuEfisPanelInputs, efis_range_knob_turns) == 0);
    assert!(offset_of!(BaseFcuEfisPanelInputs, efis_mode_knob_turns) == 1);
    assert!(offset_of!(BaseFcuEfisPanelInputs, baro_is_inhg) == 2);
    assert!(offset_of!(BaseFcuEfisPanelInputs, baro_knob) == 3);
    assert!(offset_of!(BaseFcuEfisPanelInputs, vv_button_pushed) == 6);
    assert!(offset_of!(BaseFcuEfisPanelInputs, ls_button_pushed) == 7);
    assert!(offset_of!(BaseFcuEfisPanelInputs, taxi_button_pushed) == 8);
    assert!(offset_of!(BaseFcuEfisPanelInputs, cstr_button_pushed) == 9);
    assert!(offset_of!(BaseFcuEfisPanelInputs, wpt_button_pushed) == 10);
    assert!(offset_of!(BaseFcuEfisPanelInputs, vord_button_pushed) == 11);
    assert!(offset_of!(BaseFcuEfisPanelInputs, ndb_button_pushed) == 12);
    assert!(offset_of!(BaseFcuEfisPanelInputs, arpt_button_pushed) == 13);
    assert!(offset_of!(BaseFcuEfisPanelInputs, navaid_1_button_pushed) == 14);
    assert!(offset_of!(BaseFcuEfisPanelInputs, navaid_2_button_pushed) == 15);
    assert!(offset_of!(BaseFcuEfisPanelInputs, wx_button_pushed) == 16);
    assert!(offset_of!(BaseFcuEfisPanelInputs, terr_button_pushed) == 17);
    assert!(offset_of!(BaseFcuEfisPanelInputs, traf_button_pushed) == 18);
    assert!(size_of::<BaseFcuAfsPanelInputs>() == 21 && align_of::<BaseFcuAfsPanelInputs>() == 1);
    assert!(offset_of!(BaseFcuAfsPanelInputs, fd_button_pressed) == 0);
    assert!(offset_of!(BaseFcuAfsPanelInputs, loc_button_pressed) == 1);
    assert!(offset_of!(BaseFcuAfsPanelInputs, alt_button_pressed) == 2);
    assert!(offset_of!(BaseFcuAfsPanelInputs, appr_button_pressed) == 3);
    assert!(offset_of!(BaseFcuAfsPanelInputs, spd_mach_button_pressed) == 4);
    assert!(offset_of!(BaseFcuAfsPanelInputs, true_mag_button_pressed) == 5);
    assert!(offset_of!(BaseFcuAfsPanelInputs, trk_fpa_button_pressed) == 6);
    assert!(offset_of!(BaseFcuAfsPanelInputs, metric_alt_button_pressed) == 7);
    assert!(offset_of!(BaseFcuAfsPanelInputs, spd_knob) == 8);
    assert!(offset_of!(BaseFcuAfsPanelInputs, hdg_trk_knob) == 11);
    assert!(offset_of!(BaseFcuAfsPanelInputs, alt_knob) == 14);
    assert!(offset_of!(BaseFcuAfsPanelInputs, alt_increment_1000) == 17);
    assert!(offset_of!(BaseFcuAfsPanelInputs, vs_fpa_knob) == 18);
    assert!(size_of::<BaseFcuDiscreteInputs>() == 47 && align_of::<BaseFcuDiscreteInputs>() == 1);
    assert!(offset_of!(BaseFcuDiscreteInputs, fcu_switched_off) == 0);
    assert!(offset_of!(BaseFcuDiscreteInputs, efis_backup_activated) == 1);
    assert!(offset_of!(BaseFcuDiscreteInputs, selected_by_prim_1) == 2);
    assert!(offset_of!(BaseFcuDiscreteInputs, selected_by_prim_2) == 3);
    assert!(offset_of!(BaseFcuDiscreteInputs, selected_by_prim_3) == 4);
    assert!(offset_of!(BaseFcuDiscreteInputs, lights_test) == 5);
    assert!(offset_of!(BaseFcuDiscreteInputs, pin_prog_qfe_avail) == 6);
    assert!(offset_of!(BaseFcuDiscreteInputs, efis_inputs) == 7);
    assert!(offset_of!(BaseFcuDiscreteInputs, afs_inputs) == 26);
    assert!(size_of::<BaseAesuBus>() == 8 && align_of::<BaseAesuBus>() == 4);
    assert!(offset_of!(BaseAesuBus, aesu_status_word) == 0);
    assert!(size_of::<BaseFcuBusInputs>() == 2456 && align_of::<BaseFcuBusInputs>() == 4);
    assert!(offset_of!(BaseFcuBusInputs, prim_1_bus) == 0);
    assert!(offset_of!(BaseFcuBusInputs, prim_2_bus) == 816);
    assert!(offset_of!(BaseFcuBusInputs, prim_3_bus) == 1632);
    assert!(offset_of!(BaseFcuBusInputs, aesu_bus) == 2448);
    assert!(size_of::<FcuInputs>() == 2544 && align_of::<FcuInputs>() == 8);
    assert!(offset_of!(FcuInputs, time) == 0);
    assert!(offset_of!(FcuInputs, sim_data) == 24);
    assert!(offset_of!(FcuInputs, sim_input) == 32);
    assert!(offset_of!(FcuInputs, discrete_inputs) == 40);
    assert!(offset_of!(FcuInputs, bus_inputs) == 88);
    assert!(size_of::<BaseFcuEfisPanelOutputs>() == 40 && align_of::<BaseFcuEfisPanelOutputs>() == 4);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, vv_light_on) == 0);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, ls_light_on) == 1);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, taxi_light_on) == 2);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, cstr_light_on) == 3);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, wpt_light_on) == 4);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, vord_light_on) == 5);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, ndb_light_on) == 6);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, arpt_light_on) == 7);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, traf_light_on) == 8);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, wxr_light_on) == 9);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, terr_light_on) == 10);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, navaid_1_mode) == 12);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, navaid_2_mode) == 16);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, efis_range) == 20);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, efis_mode) == 24);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, baro_is_inhg) == 28);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, baro_is_std) == 29);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, baro_value) == 32);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, baro_mode) == 36);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, baro_preset_visible) == 37);
    assert!(offset_of!(BaseFcuEfisPanelOutputs, efis_cp_active) == 38);
    assert!(size_of::<BaseFcuAfsPanelOutputs>() == 72 && align_of::<BaseFcuAfsPanelOutputs>() == 8);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, loc_light_on) == 0);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, alt_light_on) == 1);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, appr_light_on) == 2);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, ap_1_light_on) == 3);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, ap_2_light_on) == 4);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, athr_light_on) == 5);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, fd_light_on) == 6);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, trk_fpa_mode) == 7);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, true_mode) == 8);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, mach_mode) == 9);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, spd_mach_value) == 16);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, spd_mach_dashes) == 24);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, hdg_trk_value) == 32);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, hdg_trk_dashes) == 40);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, alt_value) == 48);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, vs_fpa_value) == 56);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, vs_fpa_dashes) == 64);
    assert!(offset_of!(BaseFcuAfsPanelOutputs, afs_cp_active) == 65);
    assert!(size_of::<BaseFcuDiscreteOutputs>() == 120 && align_of::<BaseFcuDiscreteOutputs>() == 8);
    assert!(offset_of!(BaseFcuDiscreteOutputs, efis_outputs) == 0);
    assert!(offset_of!(BaseFcuDiscreteOutputs, afs_outputs) == 40);
    assert!(offset_of!(BaseFcuDiscreteOutputs, true_selected) == 112);
    assert!(offset_of!(BaseFcuDiscreteOutputs, fcu_healthy) == 113);
};
